//
//  BCStyleKit.swift
//  BrainCenter
//
//  Created by Eddie Koranek on 7/16/16.
//  Copyright (c) 2016 drawChicken. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class BCStyleKit : NSObject {

    //// Cache

    private struct Cache {
        static let grapeFruitL: UIColor = UIColor(red: 0.929, green: 0.333, blue: 0.396, alpha: 1.000)
        static let bittersweetL: UIColor = UIColor(red: 0.988, green: 0.431, blue: 0.318, alpha: 1.000)
        static let sunflowerL: UIColor = UIColor(red: 1.000, green: 0.808, blue: 0.329, alpha: 1.000)
        static let grassL: UIColor = UIColor(red: 0.627, green: 0.831, blue: 0.408, alpha: 1.000)
        static let mintL: UIColor = UIColor(red: 0.282, green: 0.812, blue: 0.678, alpha: 1.000)
        static let mintD: UIColor = UIColor(red: 0.216, green: 0.737, blue: 0.608, alpha: 1.000)
        static let aquaL: UIColor = UIColor(red: 0.310, green: 0.757, blue: 0.914, alpha: 1.000)
        static let aquaD: UIColor = UIColor(red: 0.231, green: 0.686, blue: 0.855, alpha: 1.000)
        static let blueJeansL: UIColor = UIColor(red: 0.365, green: 0.612, blue: 0.925, alpha: 1.000)
        static let blueJeansD: UIColor = UIColor(red: 0.290, green: 0.537, blue: 0.863, alpha: 1.000)
        static let lavendarL: UIColor = UIColor(red: 0.675, green: 0.573, blue: 0.808, alpha: 1.000)
        static let lavendarD: UIColor = UIColor(red: 0.588, green: 0.478, blue: 0.863, alpha: 1.000)
        static let lightGrayL: UIColor = UIColor(red: 0.961, green: 0.969, blue: 0.980, alpha: 1.000)
        static let lightGrayD: UIColor = UIColor(red: 0.902, green: 0.914, blue: 0.929, alpha: 1.000)
        static let mediumGrayL: UIColor = UIColor(red: 0.800, green: 0.820, blue: 0.851, alpha: 1.000)
        static let mediumGrayD: UIColor = UIColor(red: 0.667, green: 0.698, blue: 0.741, alpha: 1.000)
        static let darkGrayL: UIColor = UIColor(red: 0.396, green: 0.427, blue: 0.471, alpha: 1.000)
        static let darkGrayD: UIColor = UIColor(red: 0.263, green: 0.290, blue: 0.329, alpha: 1.000)
        static var imageOf_5Elaborated: UIImage?
        static var _5ElaboratedTargets: [AnyObject]?
        static var imageOf_15Elaborated: UIImage?
        static var _15ElaboratedTargets: [AnyObject]?
        static var imageOf_12Elaborated: UIImage?
        static var _12ElaboratedTargets: [AnyObject]?
    }

    //// Colors

    public class var grapeFruitL: UIColor { return Cache.grapeFruitL }
    public class var bittersweetL: UIColor { return Cache.bittersweetL }
    public class var sunflowerL: UIColor { return Cache.sunflowerL }
    public class var grassL: UIColor { return Cache.grassL }
    public class var mintL: UIColor { return Cache.mintL }
    public class var mintD: UIColor { return Cache.mintD }
    public class var aquaL: UIColor { return Cache.aquaL }
    public class var aquaD: UIColor { return Cache.aquaD }
    public class var blueJeansL: UIColor { return Cache.blueJeansL }
    public class var blueJeansD: UIColor { return Cache.blueJeansD }
    public class var lavendarL: UIColor { return Cache.lavendarL }
    public class var lavendarD: UIColor { return Cache.lavendarD }
    public class var lightGrayL: UIColor { return Cache.lightGrayL }
    public class var lightGrayD: UIColor { return Cache.lightGrayD }
    public class var mediumGrayL: UIColor { return Cache.mediumGrayL }
    public class var mediumGrayD: UIColor { return Cache.mediumGrayD }
    public class var darkGrayL: UIColor { return Cache.darkGrayL }
    public class var darkGrayD: UIColor { return Cache.darkGrayD }

    //// Drawing Methods

    public class func draw_5Elaborated() {
        //// Color Declarations
        let sunflowerD = UIColor(red: 0.965, green: 0.733, blue: 0.259, alpha: 1.000)
        let grassD = UIColor(red: 0.549, green: 0.757, blue: 0.322, alpha: 1.000)

        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(rect: CGRect(x: 0, y: 0, width: 200, height: 200))
        BCStyleKit.darkGrayL.setFill()
        rectanglePath.fill()


        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPoint(x: 86.5, y: 169.92))
        bezierPath.addCurveToPoint(CGPoint(x: 95.5, y: 160.97), controlPoint1: CGPoint(x: 86.5, y: 169.92), controlPoint2: CGPoint(x: 95.5, y: 168.13))
        bezierPath.addCurveToPoint(CGPoint(x: 95.5, y: 37.45), controlPoint1: CGPoint(x: 95.5, y: 153.81), controlPoint2: CGPoint(x: 95.5, y: 37.45))
        bezierPath.addCurveToPoint(CGPoint(x: 86.5, y: 28.5), controlPoint1: CGPoint(x: 95.5, y: 37.45), controlPoint2: CGPoint(x: 95.5, y: 28.5))
        bezierPath.addCurveToPoint(CGPoint(x: 32.5, y: 118.01), controlPoint1: CGPoint(x: 77.5, y: 28.5), controlPoint2: CGPoint(x: 32.5, y: 51.77))
        bezierPath.addCurveToPoint(CGPoint(x: 86.5, y: 169.92), controlPoint1: CGPoint(x: 32.5, y: 184.25), controlPoint2: CGPoint(x: 86.5, y: 169.92))
        bezierPath.closePath()
        BCStyleKit.sunflowerL.setFill()
        bezierPath.fill()
        BCStyleKit.bittersweetL.setStroke()
        bezierPath.lineWidth = 3
        bezierPath.stroke()


        //// Bezier 2 Drawing
        let bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPoint(x: 114.5, y: 169.92))
        bezier2Path.addCurveToPoint(CGPoint(x: 105.5, y: 160.97), controlPoint1: CGPoint(x: 114.5, y: 169.92), controlPoint2: CGPoint(x: 105.5, y: 168.13))
        bezier2Path.addCurveToPoint(CGPoint(x: 105.5, y: 37.45), controlPoint1: CGPoint(x: 105.5, y: 153.81), controlPoint2: CGPoint(x: 105.5, y: 37.45))
        bezier2Path.addCurveToPoint(CGPoint(x: 114.5, y: 28.5), controlPoint1: CGPoint(x: 105.5, y: 37.45), controlPoint2: CGPoint(x: 105.5, y: 28.5))
        bezier2Path.addCurveToPoint(CGPoint(x: 168.5, y: 118.01), controlPoint1: CGPoint(x: 123.5, y: 28.5), controlPoint2: CGPoint(x: 168.5, y: 51.77))
        bezier2Path.addCurveToPoint(CGPoint(x: 114.5, y: 169.92), controlPoint1: CGPoint(x: 168.5, y: 184.25), controlPoint2: CGPoint(x: 114.5, y: 169.92))
        bezier2Path.closePath()
        BCStyleKit.grassL.setFill()
        bezier2Path.fill()
        BCStyleKit.mintD.setStroke()
        bezier2Path.lineWidth = 3
        bezier2Path.stroke()


        //// Bezier 3 Drawing
        let bezier3Path = UIBezierPath()
        bezier3Path.moveToPoint(CGPoint(x: 75, y: 45.75))
        bezier3Path.addCurveToPoint(CGPoint(x: 67.5, y: 53.5), controlPoint1: CGPoint(x: 75, y: 50.03), controlPoint2: CGPoint(x: 71.64, y: 53.5))
        bezier3Path.moveToPoint(CGPoint(x: 60, y: 61.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 67.5, y: 53.5), controlPoint1: CGPoint(x: 60, y: 56.97), controlPoint2: CGPoint(x: 63.36, y: 53.5))
        bezier3Path.moveToPoint(CGPoint(x: 60, y: 61.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 67.5, y: 69), controlPoint1: CGPoint(x: 60, y: 65.53), controlPoint2: CGPoint(x: 63.36, y: 69))
        bezier3Path.moveToPoint(CGPoint(x: 75, y: 45.75))
        bezier3Path.addCurveToPoint(CGPoint(x: 82.5, y: 38), controlPoint1: CGPoint(x: 75, y: 41.47), controlPoint2: CGPoint(x: 78.36, y: 38))
        bezier3Path.moveToPoint(CGPoint(x: 75, y: 61.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 67.5, y: 69), controlPoint1: CGPoint(x: 75, y: 65.53), controlPoint2: CGPoint(x: 71.64, y: 69))
        bezier3Path.moveToPoint(CGPoint(x: 75, y: 61.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 82.5, y: 53.5), controlPoint1: CGPoint(x: 75, y: 56.97), controlPoint2: CGPoint(x: 78.36, y: 53.5))
        bezier3Path.moveToPoint(CGPoint(x: 90, y: 61.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 82.5, y: 53.5), controlPoint1: CGPoint(x: 90, y: 56.97), controlPoint2: CGPoint(x: 86.64, y: 53.5))
        bezier3Path.moveToPoint(CGPoint(x: 90, y: 45.75))
        bezier3Path.addCurveToPoint(CGPoint(x: 82.5, y: 38), controlPoint1: CGPoint(x: 90, y: 41.47), controlPoint2: CGPoint(x: 86.64, y: 38))
        bezier3Path.moveToPoint(CGPoint(x: 90, y: 61.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 82.5, y: 69), controlPoint1: CGPoint(x: 90, y: 65.53), controlPoint2: CGPoint(x: 86.64, y: 69))
        bezier3Path.moveToPoint(CGPoint(x: 75, y: 76.75))
        bezier3Path.addCurveToPoint(CGPoint(x: 82.5, y: 69), controlPoint1: CGPoint(x: 75, y: 72.47), controlPoint2: CGPoint(x: 78.36, y: 69))
        bezier3Path.moveToPoint(CGPoint(x: 75, y: 76.75))
        bezier3Path.addCurveToPoint(CGPoint(x: 82.5, y: 84.5), controlPoint1: CGPoint(x: 75, y: 81.03), controlPoint2: CGPoint(x: 78.36, y: 84.5))
        bezier3Path.moveToPoint(CGPoint(x: 90, y: 92.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 82.5, y: 84.5), controlPoint1: CGPoint(x: 90, y: 87.97), controlPoint2: CGPoint(x: 86.64, y: 84.5))
        bezier3Path.moveToPoint(CGPoint(x: 90, y: 92.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 82.5, y: 100), controlPoint1: CGPoint(x: 90, y: 96.53), controlPoint2: CGPoint(x: 86.64, y: 100))
        bezier3Path.moveToPoint(CGPoint(x: 75, y: 92.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 82.5, y: 100), controlPoint1: CGPoint(x: 75, y: 96.53), controlPoint2: CGPoint(x: 78.36, y: 100))
        bezier3Path.moveToPoint(CGPoint(x: 75, y: 92.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 67.5, y: 84.5), controlPoint1: CGPoint(x: 75, y: 87.97), controlPoint2: CGPoint(x: 71.64, y: 84.5))
        bezier3Path.moveToPoint(CGPoint(x: 60, y: 76.75))
        bezier3Path.addCurveToPoint(CGPoint(x: 67.5, y: 84.5), controlPoint1: CGPoint(x: 60, y: 81.03), controlPoint2: CGPoint(x: 63.36, y: 84.5))
        bezier3Path.moveToPoint(CGPoint(x: 60, y: 76.75))
        bezier3Path.addCurveToPoint(CGPoint(x: 52.5, y: 69), controlPoint1: CGPoint(x: 60, y: 72.47), controlPoint2: CGPoint(x: 56.64, y: 69))
        bezier3Path.moveToPoint(CGPoint(x: 45, y: 76.75))
        bezier3Path.addCurveToPoint(CGPoint(x: 52.5, y: 69), controlPoint1: CGPoint(x: 45, y: 72.47), controlPoint2: CGPoint(x: 48.36, y: 69))
        bezier3Path.moveToPoint(CGPoint(x: 45, y: 76.75))
        bezier3Path.addCurveToPoint(CGPoint(x: 52.5, y: 84.5), controlPoint1: CGPoint(x: 45, y: 81.03), controlPoint2: CGPoint(x: 48.36, y: 84.5))
        bezier3Path.moveToPoint(CGPoint(x: 60, y: 92.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 52.5, y: 84.5), controlPoint1: CGPoint(x: 60, y: 87.97), controlPoint2: CGPoint(x: 56.64, y: 84.5))
        bezier3Path.moveToPoint(CGPoint(x: 60, y: 92.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 52.5, y: 100), controlPoint1: CGPoint(x: 60, y: 96.53), controlPoint2: CGPoint(x: 56.64, y: 100))
        bezier3Path.moveToPoint(CGPoint(x: 45, y: 107.75))
        bezier3Path.addCurveToPoint(CGPoint(x: 52.5, y: 100), controlPoint1: CGPoint(x: 45, y: 103.47), controlPoint2: CGPoint(x: 48.36, y: 100))
        bezier3Path.moveToPoint(CGPoint(x: 45, y: 107.75))
        bezier3Path.addCurveToPoint(CGPoint(x: 52.5, y: 115.5), controlPoint1: CGPoint(x: 45, y: 112.03), controlPoint2: CGPoint(x: 48.36, y: 115.5))
        bezier3Path.moveToPoint(CGPoint(x: 60, y: 107.75))
        bezier3Path.addCurveToPoint(CGPoint(x: 52.5, y: 115.5), controlPoint1: CGPoint(x: 60, y: 112.03), controlPoint2: CGPoint(x: 56.64, y: 115.5))
        bezier3Path.moveToPoint(CGPoint(x: 60, y: 107.75))
        bezier3Path.addCurveToPoint(CGPoint(x: 67.5, y: 100), controlPoint1: CGPoint(x: 60, y: 103.47), controlPoint2: CGPoint(x: 63.36, y: 100))
        bezier3Path.moveToPoint(CGPoint(x: 75, y: 107.75))
        bezier3Path.addCurveToPoint(CGPoint(x: 67.5, y: 100), controlPoint1: CGPoint(x: 75, y: 103.47), controlPoint2: CGPoint(x: 71.64, y: 100))
        bezier3Path.moveToPoint(CGPoint(x: 75, y: 107.75))
        bezier3Path.addCurveToPoint(CGPoint(x: 82.5, y: 115.5), controlPoint1: CGPoint(x: 75, y: 112.03), controlPoint2: CGPoint(x: 78.36, y: 115.5))
        bezier3Path.moveToPoint(CGPoint(x: 90, y: 123.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 82.5, y: 115.5), controlPoint1: CGPoint(x: 90, y: 118.97), controlPoint2: CGPoint(x: 86.64, y: 115.5))
        bezier3Path.moveToPoint(CGPoint(x: 90, y: 123.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 82.5, y: 131), controlPoint1: CGPoint(x: 90, y: 127.53), controlPoint2: CGPoint(x: 86.64, y: 131))
        bezier3Path.moveToPoint(CGPoint(x: 75, y: 123.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 82.5, y: 131), controlPoint1: CGPoint(x: 75, y: 127.53), controlPoint2: CGPoint(x: 78.36, y: 131))
        bezier3Path.moveToPoint(CGPoint(x: 60, y: 123.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 67.5, y: 115.5), controlPoint1: CGPoint(x: 60, y: 118.97), controlPoint2: CGPoint(x: 63.36, y: 115.5))
        bezier3Path.moveToPoint(CGPoint(x: 60, y: 123.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 67.5, y: 131), controlPoint1: CGPoint(x: 60, y: 127.53), controlPoint2: CGPoint(x: 63.36, y: 131))
        bezier3Path.moveToPoint(CGPoint(x: 75, y: 138.75))
        bezier3Path.addCurveToPoint(CGPoint(x: 67.5, y: 131), controlPoint1: CGPoint(x: 75, y: 134.47), controlPoint2: CGPoint(x: 71.64, y: 131))
        bezier3Path.moveToPoint(CGPoint(x: 75, y: 123.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 67.5, y: 115.5), controlPoint1: CGPoint(x: 75, y: 118.97), controlPoint2: CGPoint(x: 71.64, y: 115.5))
        bezier3Path.moveToPoint(CGPoint(x: 75, y: 138.75))
        bezier3Path.addCurveToPoint(CGPoint(x: 82.5, y: 146.5), controlPoint1: CGPoint(x: 75, y: 143.03), controlPoint2: CGPoint(x: 78.36, y: 146.5))
        bezier3Path.moveToPoint(CGPoint(x: 90, y: 154.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 82.5, y: 146.5), controlPoint1: CGPoint(x: 90, y: 149.97), controlPoint2: CGPoint(x: 86.64, y: 146.5))
        bezier3Path.moveToPoint(CGPoint(x: 90, y: 154.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 82.5, y: 162), controlPoint1: CGPoint(x: 90, y: 158.53), controlPoint2: CGPoint(x: 86.64, y: 162))
        bezier3Path.moveToPoint(CGPoint(x: 75, y: 154.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 82.5, y: 162), controlPoint1: CGPoint(x: 75, y: 158.53), controlPoint2: CGPoint(x: 78.36, y: 162))
        bezier3Path.moveToPoint(CGPoint(x: 75, y: 154.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 67.5, y: 146.5), controlPoint1: CGPoint(x: 75, y: 149.97), controlPoint2: CGPoint(x: 71.64, y: 146.5))
        bezier3Path.moveToPoint(CGPoint(x: 60, y: 138.75))
        bezier3Path.addCurveToPoint(CGPoint(x: 67.5, y: 146.5), controlPoint1: CGPoint(x: 60, y: 143.03), controlPoint2: CGPoint(x: 63.36, y: 146.5))
        bezier3Path.moveToPoint(CGPoint(x: 60, y: 138.75))
        bezier3Path.addCurveToPoint(CGPoint(x: 52.5, y: 131), controlPoint1: CGPoint(x: 60, y: 134.47), controlPoint2: CGPoint(x: 56.64, y: 131))
        bezier3Path.moveToPoint(CGPoint(x: 45, y: 138.75))
        bezier3Path.addCurveToPoint(CGPoint(x: 52.5, y: 131), controlPoint1: CGPoint(x: 45, y: 134.47), controlPoint2: CGPoint(x: 48.36, y: 131))
        bezier3Path.moveToPoint(CGPoint(x: 45, y: 138.75))
        bezier3Path.addCurveToPoint(CGPoint(x: 52.5, y: 146.5), controlPoint1: CGPoint(x: 45, y: 143.03), controlPoint2: CGPoint(x: 48.36, y: 146.5))
        bezier3Path.moveToPoint(CGPoint(x: 60, y: 154.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 52.5, y: 146.5), controlPoint1: CGPoint(x: 60, y: 149.97), controlPoint2: CGPoint(x: 56.64, y: 146.5))
        bezier3Path.moveToPoint(CGPoint(x: 60, y: 154.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 67.5, y: 162), controlPoint1: CGPoint(x: 60, y: 158.53), controlPoint2: CGPoint(x: 63.36, y: 162))
        bezier3Path.lineCapStyle = .Round;

        sunflowerD.setStroke()
        bezier3Path.lineWidth = 2
        bezier3Path.stroke()


        //// Bezier 4 Drawing
        let bezier4Path = UIBezierPath()
        bezier4Path.moveToPoint(CGPoint(x: 112, y: 45.75))
        bezier4Path.addLineToPoint(CGPoint(x: 112, y: 45.09))
        bezier4Path.addCurveToPoint(CGPoint(x: 112.29, y: 41.11), controlPoint1: CGPoint(x: 112, y: 43.05), controlPoint2: CGPoint(x: 112, y: 42.03))
        bezier4Path.addLineToPoint(CGPoint(x: 112.34, y: 40.93))
        bezier4Path.addCurveToPoint(CGPoint(x: 114.83, y: 38.35), controlPoint1: CGPoint(x: 112.76, y: 39.73), controlPoint2: CGPoint(x: 113.67, y: 38.78))
        bezier4Path.addCurveToPoint(CGPoint(x: 118.84, y: 38), controlPoint1: CGPoint(x: 115.89, y: 38), controlPoint2: CGPoint(x: 116.87, y: 38))
        bezier4Path.addLineToPoint(CGPoint(x: 119.48, y: 38))
        bezier4Path.moveToPoint(CGPoint(x: 126.02, y: 45.75))
        bezier4Path.addLineToPoint(CGPoint(x: 126.02, y: 45.09))
        bezier4Path.addCurveToPoint(CGPoint(x: 125.73, y: 41.11), controlPoint1: CGPoint(x: 126.02, y: 43.05), controlPoint2: CGPoint(x: 126.02, y: 42.03))
        bezier4Path.addLineToPoint(CGPoint(x: 125.69, y: 40.93))
        bezier4Path.addCurveToPoint(CGPoint(x: 123.2, y: 38.35), controlPoint1: CGPoint(x: 125.27, y: 39.73), controlPoint2: CGPoint(x: 124.35, y: 38.78))
        bezier4Path.addCurveToPoint(CGPoint(x: 119.18, y: 38), controlPoint1: CGPoint(x: 122.14, y: 38), controlPoint2: CGPoint(x: 121.15, y: 38))
        bezier4Path.addLineToPoint(CGPoint(x: 118.54, y: 38))
        bezier4Path.moveToPoint(CGPoint(x: 126.02, y: 44.78))
        bezier4Path.addLineToPoint(CGPoint(x: 126.02, y: 45.44))
        bezier4Path.addCurveToPoint(CGPoint(x: 126.31, y: 49.42), controlPoint1: CGPoint(x: 126.02, y: 47.48), controlPoint2: CGPoint(x: 126.02, y: 48.5))
        bezier4Path.addLineToPoint(CGPoint(x: 126.36, y: 49.6))
        bezier4Path.addCurveToPoint(CGPoint(x: 128.85, y: 52.18), controlPoint1: CGPoint(x: 126.78, y: 50.8), controlPoint2: CGPoint(x: 127.69, y: 51.75))
        bezier4Path.addCurveToPoint(CGPoint(x: 132.86, y: 52.53), controlPoint1: CGPoint(x: 129.91, y: 52.53), controlPoint2: CGPoint(x: 130.89, y: 52.53))
        bezier4Path.addLineToPoint(CGPoint(x: 133.5, y: 52.53))
        bezier4Path.moveToPoint(CGPoint(x: 140.98, y: 60.28))
        bezier4Path.addLineToPoint(CGPoint(x: 140.98, y: 59.62))
        bezier4Path.addCurveToPoint(CGPoint(x: 140.69, y: 55.64), controlPoint1: CGPoint(x: 140.98, y: 57.58), controlPoint2: CGPoint(x: 140.98, y: 56.56))
        bezier4Path.addLineToPoint(CGPoint(x: 140.64, y: 55.46))
        bezier4Path.addCurveToPoint(CGPoint(x: 138.15, y: 52.88), controlPoint1: CGPoint(x: 140.22, y: 54.26), controlPoint2: CGPoint(x: 139.31, y: 53.32))
        bezier4Path.addCurveToPoint(CGPoint(x: 134.14, y: 52.53), controlPoint1: CGPoint(x: 137.09, y: 52.53), controlPoint2: CGPoint(x: 136.11, y: 52.53))
        bezier4Path.addLineToPoint(CGPoint(x: 133.5, y: 52.53))
        bezier4Path.moveToPoint(CGPoint(x: 140.98, y: 59.31))
        bezier4Path.addLineToPoint(CGPoint(x: 140.98, y: 59.97))
        bezier4Path.addCurveToPoint(CGPoint(x: 140.69, y: 63.96), controlPoint1: CGPoint(x: 140.98, y: 62.02), controlPoint2: CGPoint(x: 140.98, y: 63.04))
        bezier4Path.addLineToPoint(CGPoint(x: 140.64, y: 64.13))
        bezier4Path.addCurveToPoint(CGPoint(x: 138.15, y: 66.72), controlPoint1: CGPoint(x: 140.22, y: 65.33), controlPoint2: CGPoint(x: 139.31, y: 66.28))
        bezier4Path.addCurveToPoint(CGPoint(x: 134.14, y: 67.06), controlPoint1: CGPoint(x: 137.09, y: 67.06), controlPoint2: CGPoint(x: 136.11, y: 67.06))
        bezier4Path.addLineToPoint(CGPoint(x: 133.5, y: 67.06))
        bezier4Path.moveToPoint(CGPoint(x: 126.02, y: 59.31))
        bezier4Path.addLineToPoint(CGPoint(x: 126.02, y: 59.97))
        bezier4Path.addCurveToPoint(CGPoint(x: 126.31, y: 63.96), controlPoint1: CGPoint(x: 126.02, y: 62.02), controlPoint2: CGPoint(x: 126.02, y: 63.04))
        bezier4Path.addLineToPoint(CGPoint(x: 126.36, y: 64.13))
        bezier4Path.addCurveToPoint(CGPoint(x: 128.85, y: 66.72), controlPoint1: CGPoint(x: 126.78, y: 65.33), controlPoint2: CGPoint(x: 127.69, y: 66.28))
        bezier4Path.addCurveToPoint(CGPoint(x: 132.86, y: 67.06), controlPoint1: CGPoint(x: 129.91, y: 67.06), controlPoint2: CGPoint(x: 130.89, y: 67.06))
        bezier4Path.addLineToPoint(CGPoint(x: 133.5, y: 67.06))
        bezier4Path.moveToPoint(CGPoint(x: 126.02, y: 60.28))
        bezier4Path.addLineToPoint(CGPoint(x: 126.02, y: 59.62))
        bezier4Path.addCurveToPoint(CGPoint(x: 125.73, y: 55.64), controlPoint1: CGPoint(x: 126.02, y: 57.58), controlPoint2: CGPoint(x: 126.02, y: 56.56))
        bezier4Path.addLineToPoint(CGPoint(x: 125.69, y: 55.46))
        bezier4Path.addCurveToPoint(CGPoint(x: 123.2, y: 52.88), controlPoint1: CGPoint(x: 125.27, y: 54.26), controlPoint2: CGPoint(x: 124.35, y: 53.32))
        bezier4Path.addCurveToPoint(CGPoint(x: 119.18, y: 52.53), controlPoint1: CGPoint(x: 122.14, y: 52.53), controlPoint2: CGPoint(x: 121.15, y: 52.53))
        bezier4Path.addLineToPoint(CGPoint(x: 118.54, y: 52.53))
        bezier4Path.moveToPoint(CGPoint(x: 112, y: 60.28))
        bezier4Path.addLineToPoint(CGPoint(x: 112, y: 59.62))
        bezier4Path.addCurveToPoint(CGPoint(x: 112.29, y: 55.64), controlPoint1: CGPoint(x: 112, y: 57.58), controlPoint2: CGPoint(x: 112, y: 56.56))
        bezier4Path.addLineToPoint(CGPoint(x: 112.34, y: 55.46))
        bezier4Path.addCurveToPoint(CGPoint(x: 114.83, y: 52.88), controlPoint1: CGPoint(x: 112.76, y: 54.26), controlPoint2: CGPoint(x: 113.67, y: 53.32))
        bezier4Path.addCurveToPoint(CGPoint(x: 118.84, y: 52.53), controlPoint1: CGPoint(x: 115.89, y: 52.53), controlPoint2: CGPoint(x: 116.87, y: 52.53))
        bezier4Path.addLineToPoint(CGPoint(x: 119.48, y: 52.53))
        bezier4Path.moveToPoint(CGPoint(x: 112, y: 60.28))
        bezier4Path.addLineToPoint(CGPoint(x: 112, y: 60.94))
        bezier4Path.addCurveToPoint(CGPoint(x: 112.29, y: 64.92), controlPoint1: CGPoint(x: 112, y: 62.98), controlPoint2: CGPoint(x: 112, y: 64))
        bezier4Path.addLineToPoint(CGPoint(x: 112.34, y: 65.1))
        bezier4Path.addCurveToPoint(CGPoint(x: 114.83, y: 67.68), controlPoint1: CGPoint(x: 112.76, y: 66.3), controlPoint2: CGPoint(x: 113.67, y: 67.25))
        bezier4Path.addCurveToPoint(CGPoint(x: 118.84, y: 68.03), controlPoint1: CGPoint(x: 115.89, y: 68.03), controlPoint2: CGPoint(x: 116.87, y: 68.03))
        bezier4Path.addLineToPoint(CGPoint(x: 119.48, y: 68.03))
        bezier4Path.moveToPoint(CGPoint(x: 126.02, y: 75.78))
        bezier4Path.addLineToPoint(CGPoint(x: 126.02, y: 75.12))
        bezier4Path.addCurveToPoint(CGPoint(x: 125.73, y: 71.14), controlPoint1: CGPoint(x: 126.02, y: 73.08), controlPoint2: CGPoint(x: 126.02, y: 72.06))
        bezier4Path.addLineToPoint(CGPoint(x: 125.69, y: 70.96))
        bezier4Path.addCurveToPoint(CGPoint(x: 123.2, y: 68.38), controlPoint1: CGPoint(x: 125.27, y: 69.76), controlPoint2: CGPoint(x: 124.35, y: 68.82))
        bezier4Path.addCurveToPoint(CGPoint(x: 119.18, y: 68.03), controlPoint1: CGPoint(x: 122.14, y: 68.03), controlPoint2: CGPoint(x: 121.15, y: 68.03))
        bezier4Path.addLineToPoint(CGPoint(x: 118.54, y: 68.03))
        bezier4Path.moveToPoint(CGPoint(x: 126.02, y: 74.81))
        bezier4Path.addLineToPoint(CGPoint(x: 126.02, y: 75.47))
        bezier4Path.addCurveToPoint(CGPoint(x: 125.73, y: 79.46), controlPoint1: CGPoint(x: 126.02, y: 77.52), controlPoint2: CGPoint(x: 126.02, y: 78.54))
        bezier4Path.addLineToPoint(CGPoint(x: 125.69, y: 79.63))
        bezier4Path.addCurveToPoint(CGPoint(x: 123.2, y: 82.22), controlPoint1: CGPoint(x: 125.27, y: 80.83), controlPoint2: CGPoint(x: 124.35, y: 81.78))
        bezier4Path.addCurveToPoint(CGPoint(x: 119.18, y: 82.56), controlPoint1: CGPoint(x: 122.14, y: 82.56), controlPoint2: CGPoint(x: 121.15, y: 82.56))
        bezier4Path.addLineToPoint(CGPoint(x: 118.54, y: 82.56))
        bezier4Path.moveToPoint(CGPoint(x: 112, y: 90.31))
        bezier4Path.addLineToPoint(CGPoint(x: 112, y: 89.65))
        bezier4Path.addCurveToPoint(CGPoint(x: 112.29, y: 85.67), controlPoint1: CGPoint(x: 112, y: 87.61), controlPoint2: CGPoint(x: 112, y: 86.59))
        bezier4Path.addLineToPoint(CGPoint(x: 112.34, y: 85.49))
        bezier4Path.addCurveToPoint(CGPoint(x: 114.83, y: 82.91), controlPoint1: CGPoint(x: 112.76, y: 84.29), controlPoint2: CGPoint(x: 113.67, y: 83.35))
        bezier4Path.addCurveToPoint(CGPoint(x: 118.84, y: 82.56), controlPoint1: CGPoint(x: 115.89, y: 82.56), controlPoint2: CGPoint(x: 116.87, y: 82.56))
        bezier4Path.addLineToPoint(CGPoint(x: 119.48, y: 82.56))
        bezier4Path.moveToPoint(CGPoint(x: 112, y: 90.31))
        bezier4Path.addLineToPoint(CGPoint(x: 112, y: 90.97))
        bezier4Path.addCurveToPoint(CGPoint(x: 112.29, y: 94.96), controlPoint1: CGPoint(x: 112, y: 93.02), controlPoint2: CGPoint(x: 112, y: 94.04))
        bezier4Path.addLineToPoint(CGPoint(x: 112.34, y: 95.13))
        bezier4Path.addCurveToPoint(CGPoint(x: 114.83, y: 97.72), controlPoint1: CGPoint(x: 112.76, y: 96.33), controlPoint2: CGPoint(x: 113.67, y: 97.28))
        bezier4Path.addCurveToPoint(CGPoint(x: 118.84, y: 98.06), controlPoint1: CGPoint(x: 115.89, y: 98.06), controlPoint2: CGPoint(x: 116.87, y: 98.06))
        bezier4Path.addLineToPoint(CGPoint(x: 119.48, y: 98.06))
        bezier4Path.moveToPoint(CGPoint(x: 126.02, y: 90.31))
        bezier4Path.addLineToPoint(CGPoint(x: 126.02, y: 90.97))
        bezier4Path.addCurveToPoint(CGPoint(x: 125.73, y: 94.96), controlPoint1: CGPoint(x: 126.02, y: 93.02), controlPoint2: CGPoint(x: 126.02, y: 94.04))
        bezier4Path.addLineToPoint(CGPoint(x: 125.69, y: 95.13))
        bezier4Path.addCurveToPoint(CGPoint(x: 123.2, y: 97.72), controlPoint1: CGPoint(x: 125.27, y: 96.33), controlPoint2: CGPoint(x: 124.35, y: 97.28))
        bezier4Path.addCurveToPoint(CGPoint(x: 119.18, y: 98.06), controlPoint1: CGPoint(x: 122.14, y: 98.06), controlPoint2: CGPoint(x: 121.15, y: 98.06))
        bezier4Path.addLineToPoint(CGPoint(x: 118.54, y: 98.06))
        bezier4Path.moveToPoint(CGPoint(x: 126.02, y: 90.31))
        bezier4Path.addLineToPoint(CGPoint(x: 126.02, y: 89.65))
        bezier4Path.addCurveToPoint(CGPoint(x: 126.31, y: 85.67), controlPoint1: CGPoint(x: 126.02, y: 87.61), controlPoint2: CGPoint(x: 126.02, y: 86.59))
        bezier4Path.addLineToPoint(CGPoint(x: 126.36, y: 85.49))
        bezier4Path.addCurveToPoint(CGPoint(x: 128.85, y: 82.91), controlPoint1: CGPoint(x: 126.78, y: 84.29), controlPoint2: CGPoint(x: 127.69, y: 83.35))
        bezier4Path.addCurveToPoint(CGPoint(x: 132.86, y: 82.56), controlPoint1: CGPoint(x: 129.91, y: 82.56), controlPoint2: CGPoint(x: 130.89, y: 82.56))
        bezier4Path.addLineToPoint(CGPoint(x: 133.5, y: 82.56))
        bezier4Path.moveToPoint(CGPoint(x: 140.04, y: 74.81))
        bezier4Path.addLineToPoint(CGPoint(x: 140.04, y: 75.47))
        bezier4Path.addCurveToPoint(CGPoint(x: 139.75, y: 79.46), controlPoint1: CGPoint(x: 140.04, y: 77.52), controlPoint2: CGPoint(x: 140.04, y: 78.54))
        bezier4Path.addLineToPoint(CGPoint(x: 139.71, y: 79.63))
        bezier4Path.addCurveToPoint(CGPoint(x: 137.22, y: 82.22), controlPoint1: CGPoint(x: 139.29, y: 80.83), controlPoint2: CGPoint(x: 138.38, y: 81.78))
        bezier4Path.addCurveToPoint(CGPoint(x: 133.2, y: 82.56), controlPoint1: CGPoint(x: 136.16, y: 82.56), controlPoint2: CGPoint(x: 135.17, y: 82.56))
        bezier4Path.addLineToPoint(CGPoint(x: 132.57, y: 82.56))
        bezier4Path.moveToPoint(CGPoint(x: 140.04, y: 75.78))
        bezier4Path.addLineToPoint(CGPoint(x: 140.04, y: 75.12))
        bezier4Path.addCurveToPoint(CGPoint(x: 140.34, y: 71.14), controlPoint1: CGPoint(x: 140.04, y: 73.08), controlPoint2: CGPoint(x: 140.04, y: 72.06))
        bezier4Path.addLineToPoint(CGPoint(x: 140.38, y: 70.96))
        bezier4Path.addCurveToPoint(CGPoint(x: 142.87, y: 68.38), controlPoint1: CGPoint(x: 140.8, y: 69.76), controlPoint2: CGPoint(x: 141.71, y: 68.82))
        bezier4Path.addCurveToPoint(CGPoint(x: 146.88, y: 68.03), controlPoint1: CGPoint(x: 143.93, y: 68.03), controlPoint2: CGPoint(x: 144.91, y: 68.03))
        bezier4Path.addLineToPoint(CGPoint(x: 147.52, y: 68.03))
        bezier4Path.moveToPoint(CGPoint(x: 154.07, y: 75.78))
        bezier4Path.addLineToPoint(CGPoint(x: 154.07, y: 75.12))
        bezier4Path.addCurveToPoint(CGPoint(x: 153.77, y: 71.14), controlPoint1: CGPoint(x: 154.07, y: 73.08), controlPoint2: CGPoint(x: 154.07, y: 72.06))
        bezier4Path.addLineToPoint(CGPoint(x: 153.73, y: 70.96))
        bezier4Path.addCurveToPoint(CGPoint(x: 151.24, y: 68.38), controlPoint1: CGPoint(x: 153.31, y: 69.76), controlPoint2: CGPoint(x: 152.4, y: 68.82))
        bezier4Path.addCurveToPoint(CGPoint(x: 147.23, y: 68.03), controlPoint1: CGPoint(x: 150.18, y: 68.03), controlPoint2: CGPoint(x: 149.19, y: 68.03))
        bezier4Path.addLineToPoint(CGPoint(x: 146.59, y: 68.03))
        bezier4Path.moveToPoint(CGPoint(x: 154.07, y: 75.78))
        bezier4Path.addLineToPoint(CGPoint(x: 154.07, y: 76.44))
        bezier4Path.addCurveToPoint(CGPoint(x: 153.77, y: 80.42), controlPoint1: CGPoint(x: 154.07, y: 78.48), controlPoint2: CGPoint(x: 154.07, y: 79.5))
        bezier4Path.addLineToPoint(CGPoint(x: 153.73, y: 80.6))
        bezier4Path.addCurveToPoint(CGPoint(x: 151.24, y: 83.18), controlPoint1: CGPoint(x: 153.31, y: 81.8), controlPoint2: CGPoint(x: 152.4, y: 82.75))
        bezier4Path.addCurveToPoint(CGPoint(x: 147.23, y: 83.53), controlPoint1: CGPoint(x: 150.18, y: 83.53), controlPoint2: CGPoint(x: 149.19, y: 83.53))
        bezier4Path.addLineToPoint(CGPoint(x: 146.59, y: 83.53))
        bezier4Path.moveToPoint(CGPoint(x: 139.11, y: 91.28))
        bezier4Path.addLineToPoint(CGPoint(x: 139.11, y: 90.62))
        bezier4Path.addCurveToPoint(CGPoint(x: 139.4, y: 86.64), controlPoint1: CGPoint(x: 139.11, y: 88.58), controlPoint2: CGPoint(x: 139.11, y: 87.56))
        bezier4Path.addLineToPoint(CGPoint(x: 139.44, y: 86.46))
        bezier4Path.addCurveToPoint(CGPoint(x: 141.93, y: 83.88), controlPoint1: CGPoint(x: 139.87, y: 85.26), controlPoint2: CGPoint(x: 140.78, y: 84.32))
        bezier4Path.addCurveToPoint(CGPoint(x: 145.95, y: 83.53), controlPoint1: CGPoint(x: 142.99, y: 83.53), controlPoint2: CGPoint(x: 143.98, y: 83.53))
        bezier4Path.addLineToPoint(CGPoint(x: 146.59, y: 83.53))
        bezier4Path.moveToPoint(CGPoint(x: 139.11, y: 90.31))
        bezier4Path.addLineToPoint(CGPoint(x: 139.11, y: 90.97))
        bezier4Path.addCurveToPoint(CGPoint(x: 139.4, y: 94.96), controlPoint1: CGPoint(x: 139.11, y: 93.02), controlPoint2: CGPoint(x: 139.11, y: 94.04))
        bezier4Path.addLineToPoint(CGPoint(x: 139.44, y: 95.13))
        bezier4Path.addCurveToPoint(CGPoint(x: 141.93, y: 97.72), controlPoint1: CGPoint(x: 139.87, y: 96.33), controlPoint2: CGPoint(x: 140.78, y: 97.28))
        bezier4Path.addCurveToPoint(CGPoint(x: 145.95, y: 98.06), controlPoint1: CGPoint(x: 142.99, y: 98.06), controlPoint2: CGPoint(x: 143.98, y: 98.06))
        bezier4Path.addLineToPoint(CGPoint(x: 146.59, y: 98.06))
        bezier4Path.moveToPoint(CGPoint(x: 154.07, y: 105.81))
        bezier4Path.addLineToPoint(CGPoint(x: 154.07, y: 105.15))
        bezier4Path.addCurveToPoint(CGPoint(x: 153.77, y: 101.17), controlPoint1: CGPoint(x: 154.07, y: 103.11), controlPoint2: CGPoint(x: 154.07, y: 102.09))
        bezier4Path.addLineToPoint(CGPoint(x: 153.73, y: 100.99))
        bezier4Path.addCurveToPoint(CGPoint(x: 151.24, y: 98.41), controlPoint1: CGPoint(x: 153.31, y: 99.79), controlPoint2: CGPoint(x: 152.4, y: 98.85))
        bezier4Path.addCurveToPoint(CGPoint(x: 147.23, y: 98.06), controlPoint1: CGPoint(x: 150.18, y: 98.06), controlPoint2: CGPoint(x: 149.19, y: 98.06))
        bezier4Path.addLineToPoint(CGPoint(x: 146.59, y: 98.06))
        bezier4Path.moveToPoint(CGPoint(x: 154.07, y: 105.81))
        bezier4Path.addLineToPoint(CGPoint(x: 154.07, y: 106.47))
        bezier4Path.addCurveToPoint(CGPoint(x: 153.77, y: 110.46), controlPoint1: CGPoint(x: 154.07, y: 108.52), controlPoint2: CGPoint(x: 154.07, y: 109.54))
        bezier4Path.addLineToPoint(CGPoint(x: 153.73, y: 110.63))
        bezier4Path.addCurveToPoint(CGPoint(x: 151.24, y: 113.22), controlPoint1: CGPoint(x: 153.31, y: 111.83), controlPoint2: CGPoint(x: 152.4, y: 112.78))
        bezier4Path.addCurveToPoint(CGPoint(x: 147.23, y: 113.56), controlPoint1: CGPoint(x: 150.18, y: 113.56), controlPoint2: CGPoint(x: 149.19, y: 113.56))
        bezier4Path.addLineToPoint(CGPoint(x: 146.59, y: 113.56))
        bezier4Path.moveToPoint(CGPoint(x: 139.11, y: 105.81))
        bezier4Path.addLineToPoint(CGPoint(x: 139.11, y: 106.47))
        bezier4Path.addCurveToPoint(CGPoint(x: 139.4, y: 110.46), controlPoint1: CGPoint(x: 139.11, y: 108.52), controlPoint2: CGPoint(x: 139.11, y: 109.54))
        bezier4Path.addLineToPoint(CGPoint(x: 139.44, y: 110.63))
        bezier4Path.addCurveToPoint(CGPoint(x: 141.93, y: 113.22), controlPoint1: CGPoint(x: 139.87, y: 111.83), controlPoint2: CGPoint(x: 140.78, y: 112.78))
        bezier4Path.addCurveToPoint(CGPoint(x: 145.95, y: 113.56), controlPoint1: CGPoint(x: 142.99, y: 113.56), controlPoint2: CGPoint(x: 143.98, y: 113.56))
        bezier4Path.addLineToPoint(CGPoint(x: 146.59, y: 113.56))
        bezier4Path.moveToPoint(CGPoint(x: 125.09, y: 106.78))
        bezier4Path.addLineToPoint(CGPoint(x: 125.09, y: 106.12))
        bezier4Path.addCurveToPoint(CGPoint(x: 125.38, y: 102.14), controlPoint1: CGPoint(x: 125.09, y: 104.08), controlPoint2: CGPoint(x: 125.09, y: 103.06))
        bezier4Path.addLineToPoint(CGPoint(x: 125.42, y: 101.96))
        bezier4Path.addCurveToPoint(CGPoint(x: 127.91, y: 99.38), controlPoint1: CGPoint(x: 125.84, y: 100.76), controlPoint2: CGPoint(x: 126.76, y: 99.82))
        bezier4Path.addCurveToPoint(CGPoint(x: 131.93, y: 99.03), controlPoint1: CGPoint(x: 128.97, y: 99.03), controlPoint2: CGPoint(x: 129.96, y: 99.03))
        bezier4Path.addLineToPoint(CGPoint(x: 132.57, y: 99.03))
        bezier4Path.moveToPoint(CGPoint(x: 139.11, y: 106.78))
        bezier4Path.addLineToPoint(CGPoint(x: 139.11, y: 106.12))
        bezier4Path.addCurveToPoint(CGPoint(x: 138.82, y: 102.14), controlPoint1: CGPoint(x: 139.11, y: 104.08), controlPoint2: CGPoint(x: 139.11, y: 103.06))
        bezier4Path.addLineToPoint(CGPoint(x: 138.77, y: 101.96))
        bezier4Path.addCurveToPoint(CGPoint(x: 136.28, y: 99.38), controlPoint1: CGPoint(x: 138.35, y: 100.76), controlPoint2: CGPoint(x: 137.44, y: 99.82))
        bezier4Path.addCurveToPoint(CGPoint(x: 132.27, y: 99.03), controlPoint1: CGPoint(x: 135.22, y: 99.03), controlPoint2: CGPoint(x: 134.24, y: 99.03))
        bezier4Path.addLineToPoint(CGPoint(x: 131.63, y: 99.03))
        bezier4Path.moveToPoint(CGPoint(x: 125.09, y: 106.78))
        bezier4Path.addLineToPoint(CGPoint(x: 125.09, y: 107.44))
        bezier4Path.addCurveToPoint(CGPoint(x: 124.79, y: 111.42), controlPoint1: CGPoint(x: 125.09, y: 109.48), controlPoint2: CGPoint(x: 125.09, y: 110.5))
        bezier4Path.addLineToPoint(CGPoint(x: 124.75, y: 111.6))
        bezier4Path.addCurveToPoint(CGPoint(x: 122.26, y: 114.18), controlPoint1: CGPoint(x: 124.33, y: 112.8), controlPoint2: CGPoint(x: 123.42, y: 113.75))
        bezier4Path.addCurveToPoint(CGPoint(x: 118.25, y: 114.53), controlPoint1: CGPoint(x: 121.2, y: 114.53), controlPoint2: CGPoint(x: 120.22, y: 114.53))
        bezier4Path.addLineToPoint(CGPoint(x: 117.61, y: 114.53))
        bezier4Path.moveToPoint(CGPoint(x: 112, y: 122.28))
        bezier4Path.addLineToPoint(CGPoint(x: 112, y: 121.62))
        bezier4Path.addCurveToPoint(CGPoint(x: 112.29, y: 117.64), controlPoint1: CGPoint(x: 112, y: 119.58), controlPoint2: CGPoint(x: 112, y: 118.56))
        bezier4Path.addLineToPoint(CGPoint(x: 112.34, y: 117.46))
        bezier4Path.addCurveToPoint(CGPoint(x: 114.83, y: 114.88), controlPoint1: CGPoint(x: 112.76, y: 116.26), controlPoint2: CGPoint(x: 113.67, y: 115.32))
        bezier4Path.addCurveToPoint(CGPoint(x: 118.84, y: 114.53), controlPoint1: CGPoint(x: 115.89, y: 114.53), controlPoint2: CGPoint(x: 116.87, y: 114.53))
        bezier4Path.addLineToPoint(CGPoint(x: 119.48, y: 114.53))
        bezier4Path.moveToPoint(CGPoint(x: 112, y: 122.28))
        bezier4Path.addLineToPoint(CGPoint(x: 112, y: 122.94))
        bezier4Path.addCurveToPoint(CGPoint(x: 112.29, y: 126.92), controlPoint1: CGPoint(x: 112, y: 124.98), controlPoint2: CGPoint(x: 112, y: 126))
        bezier4Path.addLineToPoint(CGPoint(x: 112.34, y: 127.1))
        bezier4Path.addCurveToPoint(CGPoint(x: 114.83, y: 129.68), controlPoint1: CGPoint(x: 112.76, y: 128.3), controlPoint2: CGPoint(x: 113.67, y: 129.25))
        bezier4Path.addCurveToPoint(CGPoint(x: 118.84, y: 130.03), controlPoint1: CGPoint(x: 115.89, y: 130.03), controlPoint2: CGPoint(x: 116.87, y: 130.03))
        bezier4Path.addLineToPoint(CGPoint(x: 119.48, y: 130.03))
        bezier4Path.moveToPoint(CGPoint(x: 126.02, y: 122.28))
        bezier4Path.addLineToPoint(CGPoint(x: 126.02, y: 122.94))
        bezier4Path.addCurveToPoint(CGPoint(x: 125.73, y: 126.92), controlPoint1: CGPoint(x: 126.02, y: 124.98), controlPoint2: CGPoint(x: 126.02, y: 126))
        bezier4Path.addLineToPoint(CGPoint(x: 125.69, y: 127.1))
        bezier4Path.addCurveToPoint(CGPoint(x: 123.2, y: 129.68), controlPoint1: CGPoint(x: 125.27, y: 128.3), controlPoint2: CGPoint(x: 124.35, y: 129.25))
        bezier4Path.addCurveToPoint(CGPoint(x: 119.18, y: 130.03), controlPoint1: CGPoint(x: 122.14, y: 130.03), controlPoint2: CGPoint(x: 121.15, y: 130.03))
        bezier4Path.addLineToPoint(CGPoint(x: 118.54, y: 130.03))
        bezier4Path.moveToPoint(CGPoint(x: 126.02, y: 123.25))
        bezier4Path.addLineToPoint(CGPoint(x: 126.02, y: 122.59))
        bezier4Path.addCurveToPoint(CGPoint(x: 126.31, y: 118.61), controlPoint1: CGPoint(x: 126.02, y: 120.55), controlPoint2: CGPoint(x: 126.02, y: 119.53))
        bezier4Path.addLineToPoint(CGPoint(x: 126.36, y: 118.43))
        bezier4Path.addCurveToPoint(CGPoint(x: 128.85, y: 115.85), controlPoint1: CGPoint(x: 126.78, y: 117.23), controlPoint2: CGPoint(x: 127.69, y: 116.28))
        bezier4Path.addCurveToPoint(CGPoint(x: 132.86, y: 115.5), controlPoint1: CGPoint(x: 129.91, y: 115.5), controlPoint2: CGPoint(x: 130.89, y: 115.5))
        bezier4Path.addLineToPoint(CGPoint(x: 133.5, y: 115.5))
        bezier4Path.moveToPoint(CGPoint(x: 140.04, y: 123.25))
        bezier4Path.addLineToPoint(CGPoint(x: 140.04, y: 122.59))
        bezier4Path.addCurveToPoint(CGPoint(x: 139.75, y: 118.61), controlPoint1: CGPoint(x: 140.04, y: 120.55), controlPoint2: CGPoint(x: 140.04, y: 119.53))
        bezier4Path.addLineToPoint(CGPoint(x: 139.71, y: 118.43))
        bezier4Path.addCurveToPoint(CGPoint(x: 137.22, y: 115.85), controlPoint1: CGPoint(x: 139.29, y: 117.23), controlPoint2: CGPoint(x: 138.38, y: 116.28))
        bezier4Path.addCurveToPoint(CGPoint(x: 133.2, y: 115.5), controlPoint1: CGPoint(x: 136.16, y: 115.5), controlPoint2: CGPoint(x: 135.17, y: 115.5))
        bezier4Path.addLineToPoint(CGPoint(x: 132.57, y: 115.5))
        bezier4Path.moveToPoint(CGPoint(x: 140.04, y: 123.25))
        bezier4Path.addLineToPoint(CGPoint(x: 140.04, y: 123.91))
        bezier4Path.addCurveToPoint(CGPoint(x: 139.75, y: 127.89), controlPoint1: CGPoint(x: 140.04, y: 125.95), controlPoint2: CGPoint(x: 140.04, y: 126.97))
        bezier4Path.addLineToPoint(CGPoint(x: 139.71, y: 128.07))
        bezier4Path.addCurveToPoint(CGPoint(x: 137.22, y: 130.65), controlPoint1: CGPoint(x: 139.29, y: 129.27), controlPoint2: CGPoint(x: 138.38, y: 130.22))
        bezier4Path.addCurveToPoint(CGPoint(x: 133.2, y: 131), controlPoint1: CGPoint(x: 136.16, y: 131), controlPoint2: CGPoint(x: 135.17, y: 131))
        bezier4Path.addLineToPoint(CGPoint(x: 132.57, y: 131))
        bezier4Path.moveToPoint(CGPoint(x: 126.02, y: 138.75))
        bezier4Path.addLineToPoint(CGPoint(x: 126.02, y: 138.09))
        bezier4Path.addCurveToPoint(CGPoint(x: 126.31, y: 134.11), controlPoint1: CGPoint(x: 126.02, y: 136.05), controlPoint2: CGPoint(x: 126.02, y: 135.03))
        bezier4Path.addLineToPoint(CGPoint(x: 126.36, y: 133.93))
        bezier4Path.addCurveToPoint(CGPoint(x: 128.85, y: 131.35), controlPoint1: CGPoint(x: 126.78, y: 132.73), controlPoint2: CGPoint(x: 127.69, y: 131.78))
        bezier4Path.addCurveToPoint(CGPoint(x: 132.86, y: 131), controlPoint1: CGPoint(x: 129.91, y: 131), controlPoint2: CGPoint(x: 130.89, y: 131))
        bezier4Path.addLineToPoint(CGPoint(x: 133.5, y: 131))
        bezier4Path.moveToPoint(CGPoint(x: 126.02, y: 138.75))
        bezier4Path.addLineToPoint(CGPoint(x: 126.02, y: 139.41))
        bezier4Path.addCurveToPoint(CGPoint(x: 125.73, y: 143.39), controlPoint1: CGPoint(x: 126.02, y: 141.45), controlPoint2: CGPoint(x: 126.02, y: 142.47))
        bezier4Path.addLineToPoint(CGPoint(x: 125.69, y: 143.57))
        bezier4Path.addCurveToPoint(CGPoint(x: 123.2, y: 146.15), controlPoint1: CGPoint(x: 125.27, y: 144.77), controlPoint2: CGPoint(x: 124.35, y: 145.72))
        bezier4Path.addCurveToPoint(CGPoint(x: 119.18, y: 146.5), controlPoint1: CGPoint(x: 122.14, y: 146.5), controlPoint2: CGPoint(x: 121.15, y: 146.5))
        bezier4Path.addLineToPoint(CGPoint(x: 118.54, y: 146.5))
        bezier4Path.moveToPoint(CGPoint(x: 112.93, y: 154.25))
        bezier4Path.addLineToPoint(CGPoint(x: 112.93, y: 153.59))
        bezier4Path.addCurveToPoint(CGPoint(x: 113.23, y: 149.61), controlPoint1: CGPoint(x: 112.93, y: 151.55), controlPoint2: CGPoint(x: 112.93, y: 150.53))
        bezier4Path.addLineToPoint(CGPoint(x: 113.27, y: 149.43))
        bezier4Path.addCurveToPoint(CGPoint(x: 115.76, y: 146.85), controlPoint1: CGPoint(x: 113.69, y: 148.23), controlPoint2: CGPoint(x: 114.6, y: 147.28))
        bezier4Path.addCurveToPoint(CGPoint(x: 119.77, y: 146.5), controlPoint1: CGPoint(x: 116.82, y: 146.5), controlPoint2: CGPoint(x: 117.81, y: 146.5))
        bezier4Path.addLineToPoint(CGPoint(x: 120.41, y: 146.5))
        bezier4Path.moveToPoint(CGPoint(x: 112.93, y: 154.25))
        bezier4Path.addLineToPoint(CGPoint(x: 112.93, y: 154.91))
        bezier4Path.addCurveToPoint(CGPoint(x: 113.23, y: 158.89), controlPoint1: CGPoint(x: 112.93, y: 156.95), controlPoint2: CGPoint(x: 112.93, y: 157.97))
        bezier4Path.addLineToPoint(CGPoint(x: 113.27, y: 159.07))
        bezier4Path.addCurveToPoint(CGPoint(x: 115.76, y: 161.65), controlPoint1: CGPoint(x: 113.69, y: 160.27), controlPoint2: CGPoint(x: 114.6, y: 161.22))
        bezier4Path.addCurveToPoint(CGPoint(x: 119.77, y: 162), controlPoint1: CGPoint(x: 116.82, y: 162), controlPoint2: CGPoint(x: 117.81, y: 162))
        bezier4Path.addLineToPoint(CGPoint(x: 120.41, y: 162))
        bezier4Path.moveToPoint(CGPoint(x: 126.96, y: 154.25))
        bezier4Path.addLineToPoint(CGPoint(x: 126.96, y: 154.91))
        bezier4Path.addCurveToPoint(CGPoint(x: 126.66, y: 158.89), controlPoint1: CGPoint(x: 126.96, y: 156.95), controlPoint2: CGPoint(x: 126.96, y: 157.97))
        bezier4Path.addLineToPoint(CGPoint(x: 126.62, y: 159.07))
        bezier4Path.addCurveToPoint(CGPoint(x: 124.13, y: 161.65), controlPoint1: CGPoint(x: 126.2, y: 160.27), controlPoint2: CGPoint(x: 125.29, y: 161.22))
        bezier4Path.addCurveToPoint(CGPoint(x: 120.12, y: 162), controlPoint1: CGPoint(x: 123.07, y: 162), controlPoint2: CGPoint(x: 122.09, y: 162))
        bezier4Path.addLineToPoint(CGPoint(x: 119.48, y: 162))
        bezier4Path.moveToPoint(CGPoint(x: 126.96, y: 154.25))
        bezier4Path.addLineToPoint(CGPoint(x: 126.96, y: 153.59))
        bezier4Path.addCurveToPoint(CGPoint(x: 127.25, y: 149.61), controlPoint1: CGPoint(x: 126.96, y: 151.55), controlPoint2: CGPoint(x: 126.96, y: 150.53))
        bezier4Path.addLineToPoint(CGPoint(x: 127.29, y: 149.43))
        bezier4Path.addCurveToPoint(CGPoint(x: 129.78, y: 146.85), controlPoint1: CGPoint(x: 127.71, y: 148.23), controlPoint2: CGPoint(x: 128.62, y: 147.28))
        bezier4Path.addCurveToPoint(CGPoint(x: 133.8, y: 146.5), controlPoint1: CGPoint(x: 130.84, y: 146.5), controlPoint2: CGPoint(x: 131.83, y: 146.5))
        bezier4Path.addLineToPoint(CGPoint(x: 134.43, y: 146.5))
        bezier4Path.moveToPoint(CGPoint(x: 155, y: 140.69))
        bezier4Path.addLineToPoint(CGPoint(x: 155, y: 140.03))
        bezier4Path.addCurveToPoint(CGPoint(x: 154.71, y: 136.04), controlPoint1: CGPoint(x: 155, y: 137.98), controlPoint2: CGPoint(x: 155, y: 136.96))
        bezier4Path.addLineToPoint(CGPoint(x: 154.66, y: 135.87))
        bezier4Path.addCurveToPoint(CGPoint(x: 152.17, y: 133.28), controlPoint1: CGPoint(x: 154.24, y: 134.67), controlPoint2: CGPoint(x: 153.33, y: 133.72))
        bezier4Path.addCurveToPoint(CGPoint(x: 148.16, y: 132.94), controlPoint1: CGPoint(x: 151.11, y: 132.94), controlPoint2: CGPoint(x: 150.13, y: 132.94))
        bezier4Path.addLineToPoint(CGPoint(x: 147.52, y: 132.94))
        bezier4Path.moveToPoint(CGPoint(x: 141.91, y: 140.69))
        bezier4Path.addLineToPoint(CGPoint(x: 141.91, y: 140.03))
        bezier4Path.addCurveToPoint(CGPoint(x: 142.21, y: 136.04), controlPoint1: CGPoint(x: 141.91, y: 137.98), controlPoint2: CGPoint(x: 141.91, y: 136.96))
        bezier4Path.addLineToPoint(CGPoint(x: 142.25, y: 135.87))
        bezier4Path.addCurveToPoint(CGPoint(x: 144.74, y: 133.28), controlPoint1: CGPoint(x: 142.67, y: 134.67), controlPoint2: CGPoint(x: 143.58, y: 133.72))
        bezier4Path.addCurveToPoint(CGPoint(x: 148.75, y: 132.94), controlPoint1: CGPoint(x: 145.8, y: 132.94), controlPoint2: CGPoint(x: 146.78, y: 132.94))
        bezier4Path.addLineToPoint(CGPoint(x: 149.39, y: 132.94))
        bezier4Path.moveToPoint(CGPoint(x: 141.91, y: 138.75))
        bezier4Path.addLineToPoint(CGPoint(x: 141.91, y: 139.41))
        bezier4Path.addCurveToPoint(CGPoint(x: 141.62, y: 143.39), controlPoint1: CGPoint(x: 141.91, y: 141.45), controlPoint2: CGPoint(x: 141.91, y: 142.47))
        bezier4Path.addLineToPoint(CGPoint(x: 141.58, y: 143.57))
        bezier4Path.addCurveToPoint(CGPoint(x: 139.09, y: 146.15), controlPoint1: CGPoint(x: 141.16, y: 144.77), controlPoint2: CGPoint(x: 140.24, y: 145.72))
        bezier4Path.addCurveToPoint(CGPoint(x: 135.07, y: 146.5), controlPoint1: CGPoint(x: 138.03, y: 146.5), controlPoint2: CGPoint(x: 137.04, y: 146.5))
        bezier4Path.addLineToPoint(CGPoint(x: 134.43, y: 146.5))
        bezier4Path.moveToPoint(CGPoint(x: 141.91, y: 154.25))
        bezier4Path.addLineToPoint(CGPoint(x: 141.91, y: 154.91))
        bezier4Path.addCurveToPoint(CGPoint(x: 141.62, y: 158.89), controlPoint1: CGPoint(x: 141.91, y: 156.95), controlPoint2: CGPoint(x: 141.91, y: 157.97))
        bezier4Path.addLineToPoint(CGPoint(x: 141.58, y: 159.07))
        bezier4Path.addCurveToPoint(CGPoint(x: 139.09, y: 161.65), controlPoint1: CGPoint(x: 141.16, y: 160.27), controlPoint2: CGPoint(x: 140.24, y: 161.22))
        bezier4Path.addCurveToPoint(CGPoint(x: 135.07, y: 162), controlPoint1: CGPoint(x: 138.03, y: 162), controlPoint2: CGPoint(x: 137.04, y: 162))
        bezier4Path.addLineToPoint(CGPoint(x: 134.43, y: 162))
        bezier4Path.moveToPoint(CGPoint(x: 141.91, y: 155.22))
        bezier4Path.addLineToPoint(CGPoint(x: 141.91, y: 154.56))
        bezier4Path.addCurveToPoint(CGPoint(x: 142.21, y: 150.58), controlPoint1: CGPoint(x: 141.91, y: 152.52), controlPoint2: CGPoint(x: 141.91, y: 151.5))
        bezier4Path.addLineToPoint(CGPoint(x: 142.25, y: 150.4))
        bezier4Path.addCurveToPoint(CGPoint(x: 144.74, y: 147.82), controlPoint1: CGPoint(x: 142.67, y: 149.2), controlPoint2: CGPoint(x: 143.58, y: 148.25))
        bezier4Path.addCurveToPoint(CGPoint(x: 148.75, y: 147.47), controlPoint1: CGPoint(x: 145.8, y: 147.47), controlPoint2: CGPoint(x: 146.78, y: 147.47))
        bezier4Path.addLineToPoint(CGPoint(x: 149.39, y: 147.47))
        bezier4Path.moveToPoint(CGPoint(x: 155, y: 139.72))
        bezier4Path.addLineToPoint(CGPoint(x: 155, y: 140.38))
        bezier4Path.addCurveToPoint(CGPoint(x: 154.71, y: 144.36), controlPoint1: CGPoint(x: 155, y: 142.42), controlPoint2: CGPoint(x: 155, y: 143.44))
        bezier4Path.addLineToPoint(CGPoint(x: 154.66, y: 144.54))
        bezier4Path.addCurveToPoint(CGPoint(x: 152.17, y: 147.12), controlPoint1: CGPoint(x: 154.24, y: 145.74), controlPoint2: CGPoint(x: 153.33, y: 146.68))
        bezier4Path.addCurveToPoint(CGPoint(x: 148.16, y: 147.47), controlPoint1: CGPoint(x: 151.11, y: 147.47), controlPoint2: CGPoint(x: 150.13, y: 147.47))
        bezier4Path.addLineToPoint(CGPoint(x: 147.52, y: 147.47))
        bezier4Path.lineCapStyle = .Round;

        grassD.setStroke()
        bezier4Path.lineWidth = 2
        bezier4Path.stroke()
    }

    public class func draw_15Elaborated() {
        //// Color Declarations
        let sunflowerD = UIColor(red: 0.965, green: 0.733, blue: 0.259, alpha: 1.000)

        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(rect: CGRect(x: 0, y: 0, width: 200, height: 200))
        BCStyleKit.darkGrayL.setFill()
        rectanglePath.fill()


        //// Text Drawing
        let textPath = UIBezierPath()
        textPath.moveToPoint(CGPoint(x: 137.07, y: 66.81))
        textPath.addCurveToPoint(CGPoint(x: 149.67, y: 79.77), controlPoint1: CGPoint(x: 144.09, y: 66.81), controlPoint2: CGPoint(x: 149.67, y: 71.76))
        textPath.addCurveToPoint(CGPoint(x: 137.07, y: 92.82), controlPoint1: CGPoint(x: 149.67, y: 87.51), controlPoint2: CGPoint(x: 144.09, y: 92.82))
        textPath.addCurveToPoint(CGPoint(x: 124.2, y: 79.77), controlPoint1: CGPoint(x: 130.14, y: 92.82), controlPoint2: CGPoint(x: 124.2, y: 87.78))
        textPath.addCurveToPoint(CGPoint(x: 137.07, y: 66.81), controlPoint1: CGPoint(x: 124.2, y: 72.03), controlPoint2: CGPoint(x: 130.14, y: 66.81))
        textPath.closePath()
        textPath.moveToPoint(CGPoint(x: 112.5, y: 39.09))
        textPath.addLineToPoint(CGPoint(x: 112.5, y: 102))
        textPath.addLineToPoint(CGPoint(x: 122.76, y: 102))
        textPath.addLineToPoint(CGPoint(x: 123.48, y: 95.88))
        textPath.addCurveToPoint(CGPoint(x: 137.79, y: 102.99), controlPoint1: CGPoint(x: 126.9, y: 101.19), controlPoint2: CGPoint(x: 132.39, y: 102.99))
        textPath.addCurveToPoint(CGPoint(x: 160.65, y: 79.77), controlPoint1: CGPoint(x: 150.84, y: 102.99), controlPoint2: CGPoint(x: 160.65, y: 94.35))
        textPath.addCurveToPoint(CGPoint(x: 138.06, y: 56.55), controlPoint1: CGPoint(x: 160.65, y: 64.47), controlPoint2: CGPoint(x: 151.02, y: 56.55))
        textPath.addCurveToPoint(CGPoint(x: 123.48, y: 63.66), controlPoint1: CGPoint(x: 133.38, y: 56.55), controlPoint2: CGPoint(x: 126.09, y: 59.07))
        textPath.addLineToPoint(CGPoint(x: 123.48, y: 39.09))
        textPath.addLineToPoint(CGPoint(x: 112.5, y: 39.09))
        textPath.closePath()
        textPath.lineJoinStyle = .Round;

        BCStyleKit.grassL.setFill()
        textPath.fill()
        BCStyleKit.mintD.setStroke()
        textPath.lineWidth = 2
        textPath.stroke()


        //// Text 2 Drawing
        let text2Path = UIBezierPath()
        text2Path.moveToPoint(CGPoint(x: 146.29, y: 148.13))
        text2Path.addCurveToPoint(CGPoint(x: 136.57, y: 151.82), controlPoint1: CGPoint(x: 143.59, y: 150.83), controlPoint2: CGPoint(x: 140.08, y: 151.82))
        text2Path.addCurveToPoint(CGPoint(x: 123.97, y: 138.86), controlPoint1: CGPoint(x: 129.73, y: 151.82), controlPoint2: CGPoint(x: 123.97, y: 147.32))
        text2Path.addCurveToPoint(CGPoint(x: 136.75, y: 125.72), controlPoint1: CGPoint(x: 123.97, y: 131.12), controlPoint2: CGPoint(x: 129.37, y: 125.72))
        text2Path.addCurveToPoint(CGPoint(x: 145.66, y: 129.23), controlPoint1: CGPoint(x: 139.81, y: 125.72), controlPoint2: CGPoint(x: 143.05, y: 126.89))
        text2Path.addLineToPoint(CGPoint(x: 152.59, y: 121.94))
        text2Path.addCurveToPoint(CGPoint(x: 136.57, y: 115.37), controlPoint1: CGPoint(x: 147.73, y: 117.17), controlPoint2: CGPoint(x: 142.87, y: 115.37))
        text2Path.addCurveToPoint(CGPoint(x: 112.99, y: 138.86), controlPoint1: CGPoint(x: 123.7, y: 115.37), controlPoint2: CGPoint(x: 112.99, y: 123.11))
        text2Path.addCurveToPoint(CGPoint(x: 136.57, y: 162.35), controlPoint1: CGPoint(x: 112.99, y: 154.61), controlPoint2: CGPoint(x: 123.7, y: 162.35))
        text2Path.addCurveToPoint(CGPoint(x: 153.67, y: 155.33), controlPoint1: CGPoint(x: 143.14, y: 162.35), controlPoint2: CGPoint(x: 148.54, y: 160.37))
        text2Path.addLineToPoint(CGPoint(x: 146.29, y: 148.13))
        text2Path.closePath()
        text2Path.lineJoinStyle = .Round;

        BCStyleKit.mintL.setFill()
        text2Path.fill()
        BCStyleKit.blueJeansD.setStroke()
        text2Path.lineWidth = 2
        text2Path.stroke()


        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPoint(x: 93.5, y: 169.92))
        bezierPath.addCurveToPoint(CGPoint(x: 102.5, y: 160.97), controlPoint1: CGPoint(x: 93.5, y: 169.92), controlPoint2: CGPoint(x: 102.5, y: 168.13))
        bezierPath.addCurveToPoint(CGPoint(x: 102.5, y: 37.45), controlPoint1: CGPoint(x: 102.5, y: 153.81), controlPoint2: CGPoint(x: 102.5, y: 37.45))
        bezierPath.addCurveToPoint(CGPoint(x: 93.5, y: 28.5), controlPoint1: CGPoint(x: 102.5, y: 37.45), controlPoint2: CGPoint(x: 102.5, y: 28.5))
        bezierPath.addCurveToPoint(CGPoint(x: 39.5, y: 118.01), controlPoint1: CGPoint(x: 84.5, y: 28.5), controlPoint2: CGPoint(x: 39.5, y: 51.77))
        bezierPath.addCurveToPoint(CGPoint(x: 93.5, y: 169.92), controlPoint1: CGPoint(x: 39.5, y: 184.25), controlPoint2: CGPoint(x: 93.5, y: 169.92))
        bezierPath.closePath()
        BCStyleKit.sunflowerL.setFill()
        bezierPath.fill()
        BCStyleKit.bittersweetL.setStroke()
        bezierPath.lineWidth = 3
        bezierPath.stroke()


        //// Bezier 3 Drawing
        let bezier3Path = UIBezierPath()
        bezier3Path.moveToPoint(CGPoint(x: 82, y: 45.75))
        bezier3Path.addCurveToPoint(CGPoint(x: 74.5, y: 53.5), controlPoint1: CGPoint(x: 82, y: 50.03), controlPoint2: CGPoint(x: 78.64, y: 53.5))
        bezier3Path.moveToPoint(CGPoint(x: 67, y: 61.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 74.5, y: 53.5), controlPoint1: CGPoint(x: 67, y: 56.97), controlPoint2: CGPoint(x: 70.36, y: 53.5))
        bezier3Path.moveToPoint(CGPoint(x: 67, y: 61.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 74.5, y: 69), controlPoint1: CGPoint(x: 67, y: 65.53), controlPoint2: CGPoint(x: 70.36, y: 69))
        bezier3Path.moveToPoint(CGPoint(x: 82, y: 45.75))
        bezier3Path.addCurveToPoint(CGPoint(x: 89.5, y: 38), controlPoint1: CGPoint(x: 82, y: 41.47), controlPoint2: CGPoint(x: 85.36, y: 38))
        bezier3Path.moveToPoint(CGPoint(x: 82, y: 61.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 74.5, y: 69), controlPoint1: CGPoint(x: 82, y: 65.53), controlPoint2: CGPoint(x: 78.64, y: 69))
        bezier3Path.moveToPoint(CGPoint(x: 82, y: 61.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 89.5, y: 53.5), controlPoint1: CGPoint(x: 82, y: 56.97), controlPoint2: CGPoint(x: 85.36, y: 53.5))
        bezier3Path.moveToPoint(CGPoint(x: 97, y: 61.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 89.5, y: 53.5), controlPoint1: CGPoint(x: 97, y: 56.97), controlPoint2: CGPoint(x: 93.64, y: 53.5))
        bezier3Path.moveToPoint(CGPoint(x: 97, y: 45.75))
        bezier3Path.addCurveToPoint(CGPoint(x: 89.5, y: 38), controlPoint1: CGPoint(x: 97, y: 41.47), controlPoint2: CGPoint(x: 93.64, y: 38))
        bezier3Path.moveToPoint(CGPoint(x: 97, y: 61.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 89.5, y: 69), controlPoint1: CGPoint(x: 97, y: 65.53), controlPoint2: CGPoint(x: 93.64, y: 69))
        bezier3Path.moveToPoint(CGPoint(x: 82, y: 76.75))
        bezier3Path.addCurveToPoint(CGPoint(x: 89.5, y: 69), controlPoint1: CGPoint(x: 82, y: 72.47), controlPoint2: CGPoint(x: 85.36, y: 69))
        bezier3Path.moveToPoint(CGPoint(x: 82, y: 76.75))
        bezier3Path.addCurveToPoint(CGPoint(x: 89.5, y: 84.5), controlPoint1: CGPoint(x: 82, y: 81.03), controlPoint2: CGPoint(x: 85.36, y: 84.5))
        bezier3Path.moveToPoint(CGPoint(x: 97, y: 92.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 89.5, y: 84.5), controlPoint1: CGPoint(x: 97, y: 87.97), controlPoint2: CGPoint(x: 93.64, y: 84.5))
        bezier3Path.moveToPoint(CGPoint(x: 97, y: 92.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 89.5, y: 100), controlPoint1: CGPoint(x: 97, y: 96.53), controlPoint2: CGPoint(x: 93.64, y: 100))
        bezier3Path.moveToPoint(CGPoint(x: 82, y: 92.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 89.5, y: 100), controlPoint1: CGPoint(x: 82, y: 96.53), controlPoint2: CGPoint(x: 85.36, y: 100))
        bezier3Path.moveToPoint(CGPoint(x: 82, y: 92.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 74.5, y: 84.5), controlPoint1: CGPoint(x: 82, y: 87.97), controlPoint2: CGPoint(x: 78.64, y: 84.5))
        bezier3Path.moveToPoint(CGPoint(x: 67, y: 76.75))
        bezier3Path.addCurveToPoint(CGPoint(x: 74.5, y: 84.5), controlPoint1: CGPoint(x: 67, y: 81.03), controlPoint2: CGPoint(x: 70.36, y: 84.5))
        bezier3Path.moveToPoint(CGPoint(x: 67, y: 76.75))
        bezier3Path.addCurveToPoint(CGPoint(x: 59.5, y: 69), controlPoint1: CGPoint(x: 67, y: 72.47), controlPoint2: CGPoint(x: 63.64, y: 69))
        bezier3Path.moveToPoint(CGPoint(x: 52, y: 76.75))
        bezier3Path.addCurveToPoint(CGPoint(x: 59.5, y: 69), controlPoint1: CGPoint(x: 52, y: 72.47), controlPoint2: CGPoint(x: 55.36, y: 69))
        bezier3Path.moveToPoint(CGPoint(x: 52, y: 76.75))
        bezier3Path.addCurveToPoint(CGPoint(x: 59.5, y: 84.5), controlPoint1: CGPoint(x: 52, y: 81.03), controlPoint2: CGPoint(x: 55.36, y: 84.5))
        bezier3Path.moveToPoint(CGPoint(x: 67, y: 92.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 59.5, y: 84.5), controlPoint1: CGPoint(x: 67, y: 87.97), controlPoint2: CGPoint(x: 63.64, y: 84.5))
        bezier3Path.moveToPoint(CGPoint(x: 67, y: 92.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 59.5, y: 100), controlPoint1: CGPoint(x: 67, y: 96.53), controlPoint2: CGPoint(x: 63.64, y: 100))
        bezier3Path.moveToPoint(CGPoint(x: 52, y: 107.75))
        bezier3Path.addCurveToPoint(CGPoint(x: 59.5, y: 100), controlPoint1: CGPoint(x: 52, y: 103.47), controlPoint2: CGPoint(x: 55.36, y: 100))
        bezier3Path.moveToPoint(CGPoint(x: 52, y: 107.75))
        bezier3Path.addCurveToPoint(CGPoint(x: 59.5, y: 115.5), controlPoint1: CGPoint(x: 52, y: 112.03), controlPoint2: CGPoint(x: 55.36, y: 115.5))
        bezier3Path.moveToPoint(CGPoint(x: 67, y: 107.75))
        bezier3Path.addCurveToPoint(CGPoint(x: 59.5, y: 115.5), controlPoint1: CGPoint(x: 67, y: 112.03), controlPoint2: CGPoint(x: 63.64, y: 115.5))
        bezier3Path.moveToPoint(CGPoint(x: 67, y: 107.75))
        bezier3Path.addCurveToPoint(CGPoint(x: 74.5, y: 100), controlPoint1: CGPoint(x: 67, y: 103.47), controlPoint2: CGPoint(x: 70.36, y: 100))
        bezier3Path.moveToPoint(CGPoint(x: 82, y: 107.75))
        bezier3Path.addCurveToPoint(CGPoint(x: 74.5, y: 100), controlPoint1: CGPoint(x: 82, y: 103.47), controlPoint2: CGPoint(x: 78.64, y: 100))
        bezier3Path.moveToPoint(CGPoint(x: 82, y: 107.75))
        bezier3Path.addCurveToPoint(CGPoint(x: 89.5, y: 115.5), controlPoint1: CGPoint(x: 82, y: 112.03), controlPoint2: CGPoint(x: 85.36, y: 115.5))
        bezier3Path.moveToPoint(CGPoint(x: 97, y: 123.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 89.5, y: 115.5), controlPoint1: CGPoint(x: 97, y: 118.97), controlPoint2: CGPoint(x: 93.64, y: 115.5))
        bezier3Path.moveToPoint(CGPoint(x: 97, y: 123.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 89.5, y: 131), controlPoint1: CGPoint(x: 97, y: 127.53), controlPoint2: CGPoint(x: 93.64, y: 131))
        bezier3Path.moveToPoint(CGPoint(x: 82, y: 123.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 89.5, y: 131), controlPoint1: CGPoint(x: 82, y: 127.53), controlPoint2: CGPoint(x: 85.36, y: 131))
        bezier3Path.moveToPoint(CGPoint(x: 67, y: 123.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 74.5, y: 115.5), controlPoint1: CGPoint(x: 67, y: 118.97), controlPoint2: CGPoint(x: 70.36, y: 115.5))
        bezier3Path.moveToPoint(CGPoint(x: 67, y: 123.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 74.5, y: 131), controlPoint1: CGPoint(x: 67, y: 127.53), controlPoint2: CGPoint(x: 70.36, y: 131))
        bezier3Path.moveToPoint(CGPoint(x: 82, y: 138.75))
        bezier3Path.addCurveToPoint(CGPoint(x: 74.5, y: 131), controlPoint1: CGPoint(x: 82, y: 134.47), controlPoint2: CGPoint(x: 78.64, y: 131))
        bezier3Path.moveToPoint(CGPoint(x: 82, y: 123.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 74.5, y: 115.5), controlPoint1: CGPoint(x: 82, y: 118.97), controlPoint2: CGPoint(x: 78.64, y: 115.5))
        bezier3Path.moveToPoint(CGPoint(x: 82, y: 138.75))
        bezier3Path.addCurveToPoint(CGPoint(x: 89.5, y: 146.5), controlPoint1: CGPoint(x: 82, y: 143.03), controlPoint2: CGPoint(x: 85.36, y: 146.5))
        bezier3Path.moveToPoint(CGPoint(x: 97, y: 154.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 89.5, y: 146.5), controlPoint1: CGPoint(x: 97, y: 149.97), controlPoint2: CGPoint(x: 93.64, y: 146.5))
        bezier3Path.moveToPoint(CGPoint(x: 97, y: 154.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 89.5, y: 162), controlPoint1: CGPoint(x: 97, y: 158.53), controlPoint2: CGPoint(x: 93.64, y: 162))
        bezier3Path.moveToPoint(CGPoint(x: 82, y: 154.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 89.5, y: 162), controlPoint1: CGPoint(x: 82, y: 158.53), controlPoint2: CGPoint(x: 85.36, y: 162))
        bezier3Path.moveToPoint(CGPoint(x: 82, y: 154.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 74.5, y: 146.5), controlPoint1: CGPoint(x: 82, y: 149.97), controlPoint2: CGPoint(x: 78.64, y: 146.5))
        bezier3Path.moveToPoint(CGPoint(x: 67, y: 138.75))
        bezier3Path.addCurveToPoint(CGPoint(x: 74.5, y: 146.5), controlPoint1: CGPoint(x: 67, y: 143.03), controlPoint2: CGPoint(x: 70.36, y: 146.5))
        bezier3Path.moveToPoint(CGPoint(x: 67, y: 138.75))
        bezier3Path.addCurveToPoint(CGPoint(x: 59.5, y: 131), controlPoint1: CGPoint(x: 67, y: 134.47), controlPoint2: CGPoint(x: 63.64, y: 131))
        bezier3Path.moveToPoint(CGPoint(x: 52, y: 138.75))
        bezier3Path.addCurveToPoint(CGPoint(x: 59.5, y: 131), controlPoint1: CGPoint(x: 52, y: 134.47), controlPoint2: CGPoint(x: 55.36, y: 131))
        bezier3Path.moveToPoint(CGPoint(x: 52, y: 138.75))
        bezier3Path.addCurveToPoint(CGPoint(x: 59.5, y: 146.5), controlPoint1: CGPoint(x: 52, y: 143.03), controlPoint2: CGPoint(x: 55.36, y: 146.5))
        bezier3Path.moveToPoint(CGPoint(x: 67, y: 154.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 59.5, y: 146.5), controlPoint1: CGPoint(x: 67, y: 149.97), controlPoint2: CGPoint(x: 63.64, y: 146.5))
        bezier3Path.moveToPoint(CGPoint(x: 67, y: 154.25))
        bezier3Path.addCurveToPoint(CGPoint(x: 74.5, y: 162), controlPoint1: CGPoint(x: 67, y: 158.53), controlPoint2: CGPoint(x: 70.36, y: 162))
        bezier3Path.lineCapStyle = .Round;

        sunflowerD.setStroke()
        bezier3Path.lineWidth = 2
        bezier3Path.stroke()
    }

    public class func draw_12Elaborated() {

        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(rect: CGRect(x: 0, y: 0, width: 400, height: 200))
        BCStyleKit.darkGrayL.setFill()
        rectanglePath.fill()


        //// Text Drawing
        let textPath = UIBezierPath()
        textPath.moveToPoint(CGPoint(x: 84.05, y: 92.45))
        textPath.addCurveToPoint(CGPoint(x: 91.05, y: 99.65), controlPoint1: CGPoint(x: 87.95, y: 92.45), controlPoint2: CGPoint(x: 91.05, y: 95.2))
        textPath.addCurveToPoint(CGPoint(x: 84.05, y: 106.9), controlPoint1: CGPoint(x: 91.05, y: 103.95), controlPoint2: CGPoint(x: 87.95, y: 106.9))
        textPath.addCurveToPoint(CGPoint(x: 76.9, y: 99.65), controlPoint1: CGPoint(x: 80.2, y: 106.9), controlPoint2: CGPoint(x: 76.9, y: 104.1))
        textPath.addCurveToPoint(CGPoint(x: 84.05, y: 92.45), controlPoint1: CGPoint(x: 76.9, y: 95.35), controlPoint2: CGPoint(x: 80.2, y: 92.45))
        textPath.closePath()
        textPath.moveToPoint(CGPoint(x: 70.4, y: 77.05))
        textPath.addLineToPoint(CGPoint(x: 70.4, y: 112))
        textPath.addLineToPoint(CGPoint(x: 76.1, y: 112))
        textPath.addLineToPoint(CGPoint(x: 76.5, y: 108.6))
        textPath.addCurveToPoint(CGPoint(x: 84.45, y: 112.55), controlPoint1: CGPoint(x: 78.4, y: 111.55), controlPoint2: CGPoint(x: 81.45, y: 112.55))
        textPath.addCurveToPoint(CGPoint(x: 97.15, y: 99.65), controlPoint1: CGPoint(x: 91.7, y: 112.55), controlPoint2: CGPoint(x: 97.15, y: 107.75))
        textPath.addCurveToPoint(CGPoint(x: 84.6, y: 86.75), controlPoint1: CGPoint(x: 97.15, y: 91.15), controlPoint2: CGPoint(x: 91.8, y: 86.75))
        textPath.addCurveToPoint(CGPoint(x: 76.5, y: 90.7), controlPoint1: CGPoint(x: 82, y: 86.75), controlPoint2: CGPoint(x: 77.95, y: 88.15))
        textPath.addLineToPoint(CGPoint(x: 76.5, y: 77.05))
        textPath.addLineToPoint(CGPoint(x: 70.4, y: 77.05))
        textPath.closePath()
        textPath.moveToPoint(CGPoint(x: 101.65, y: 87.35))
        textPath.addLineToPoint(CGPoint(x: 101.65, y: 112))
        textPath.addLineToPoint(CGPoint(x: 107.75, y: 112))
        textPath.addLineToPoint(CGPoint(x: 107.75, y: 99))
        textPath.addCurveToPoint(CGPoint(x: 113.9, y: 92.75), controlPoint1: CGPoint(x: 107.75, y: 94.45), controlPoint2: CGPoint(x: 110.7, y: 92.75))
        textPath.addCurveToPoint(CGPoint(x: 118.3, y: 94.35), controlPoint1: CGPoint(x: 115.9, y: 92.75), controlPoint2: CGPoint(x: 117.05, y: 93.3))
        textPath.addLineToPoint(CGPoint(x: 121.05, y: 89.05))
        textPath.addCurveToPoint(CGPoint(x: 114.7, y: 86.7), controlPoint1: CGPoint(x: 119.7, y: 87.7), controlPoint2: CGPoint(x: 117.25, y: 86.7))
        textPath.addCurveToPoint(CGPoint(x: 107.75, y: 90.2), controlPoint1: CGPoint(x: 112.2, y: 86.7), controlPoint2: CGPoint(x: 109.65, y: 87.15))
        textPath.addLineToPoint(CGPoint(x: 107.3, y: 87.35))
        textPath.addLineToPoint(CGPoint(x: 101.65, y: 87.35))
        textPath.closePath()
        textPath.moveToPoint(CGPoint(x: 142.7, y: 90.75))
        textPath.addCurveToPoint(CGPoint(x: 134.85, y: 86.75), controlPoint1: CGPoint(x: 141.3, y: 88.3), controlPoint2: CGPoint(x: 138.15, y: 86.75))
        textPath.addCurveToPoint(CGPoint(x: 122, y: 99.65), controlPoint1: CGPoint(x: 127.65, y: 86.7), controlPoint2: CGPoint(x: 122, y: 91.15))
        textPath.addCurveToPoint(CGPoint(x: 134.7, y: 112.75), controlPoint1: CGPoint(x: 122, y: 108.3), controlPoint2: CGPoint(x: 127.4, y: 112.8))
        textPath.addCurveToPoint(CGPoint(x: 142.7, y: 108.4), controlPoint1: CGPoint(x: 137.45, y: 112.7), controlPoint2: CGPoint(x: 141.3, y: 111.3))
        textPath.addLineToPoint(CGPoint(x: 143, y: 112))
        textPath.addLineToPoint(CGPoint(x: 148.75, y: 112))
        textPath.addLineToPoint(CGPoint(x: 148.75, y: 87.35))
        textPath.addLineToPoint(CGPoint(x: 142.9, y: 87.35))
        textPath.addLineToPoint(CGPoint(x: 142.7, y: 90.75))
        textPath.closePath()
        textPath.moveToPoint(CGPoint(x: 135.4, y: 92.2))
        textPath.addCurveToPoint(CGPoint(x: 135.4, y: 107.15), controlPoint1: CGPoint(x: 145, y: 92.2), controlPoint2: CGPoint(x: 145, y: 107.15))
        textPath.addCurveToPoint(CGPoint(x: 128.1, y: 99.65), controlPoint1: CGPoint(x: 131.35, y: 107.15), controlPoint2: CGPoint(x: 128.1, y: 104.35))
        textPath.addCurveToPoint(CGPoint(x: 135.4, y: 92.2), controlPoint1: CGPoint(x: 128.1, y: 94.95), controlPoint2: CGPoint(x: 131.35, y: 92.2))
        textPath.closePath()
        textPath.moveToPoint(CGPoint(x: 160, y: 87.25))
        textPath.addLineToPoint(CGPoint(x: 160, y: 112))
        textPath.addLineToPoint(CGPoint(x: 153.9, y: 112))
        textPath.addLineToPoint(CGPoint(x: 153.9, y: 87.25))
        textPath.addLineToPoint(CGPoint(x: 160, y: 87.25))
        textPath.closePath()
        textPath.moveToPoint(CGPoint(x: 153.35, y: 80.4))
        textPath.addCurveToPoint(CGPoint(x: 160.55, y: 80.4), controlPoint1: CGPoint(x: 153.35, y: 75.65), controlPoint2: CGPoint(x: 160.55, y: 75.65))
        textPath.addCurveToPoint(CGPoint(x: 153.35, y: 80.4), controlPoint1: CGPoint(x: 160.55, y: 85.15), controlPoint2: CGPoint(x: 153.35, y: 85.15))
        textPath.closePath()
        textPath.moveToPoint(CGPoint(x: 189.75, y: 112))
        textPath.addLineToPoint(CGPoint(x: 189.75, y: 99.05))
        textPath.addCurveToPoint(CGPoint(x: 179.3, y: 86.95), controlPoint1: CGPoint(x: 189.75, y: 91.3), controlPoint2: CGPoint(x: 185.1, y: 86.95))
        textPath.addCurveToPoint(CGPoint(x: 171.2, y: 90.65), controlPoint1: CGPoint(x: 176.2, y: 86.95), controlPoint2: CGPoint(x: 173.7, y: 88.2))
        textPath.addLineToPoint(CGPoint(x: 170.8, y: 87.3))
        textPath.addLineToPoint(CGPoint(x: 165.35, y: 87.3))
        textPath.addLineToPoint(CGPoint(x: 165.35, y: 112))
        textPath.addLineToPoint(CGPoint(x: 171.4, y: 112))
        textPath.addLineToPoint(CGPoint(x: 171.4, y: 99.4))
        textPath.addCurveToPoint(CGPoint(x: 177.7, y: 92.5), controlPoint1: CGPoint(x: 171.4, y: 95.65), controlPoint2: CGPoint(x: 173.95, y: 92.5))
        textPath.addCurveToPoint(CGPoint(x: 183.65, y: 99.1), controlPoint1: CGPoint(x: 181.6, y: 92.5), controlPoint2: CGPoint(x: 183.65, y: 95.35))
        textPath.addLineToPoint(CGPoint(x: 183.65, y: 112))
        textPath.addLineToPoint(CGPoint(x: 189.75, y: 112))
        textPath.closePath()
        textPath.lineJoinStyle = .Round;

        BCStyleKit.sunflowerL.setFill()
        textPath.fill()


        //// Text 2 Drawing
        let text2Path = UIBezierPath()
        text2Path.moveToPoint(CGPoint(x: 215.05, y: 104.85))
        text2Path.addCurveToPoint(CGPoint(x: 209.65, y: 106.9), controlPoint1: CGPoint(x: 213.55, y: 106.35), controlPoint2: CGPoint(x: 211.6, y: 106.9))
        text2Path.addCurveToPoint(CGPoint(x: 202.65, y: 99.7), controlPoint1: CGPoint(x: 205.85, y: 106.9), controlPoint2: CGPoint(x: 202.65, y: 104.4))
        text2Path.addCurveToPoint(CGPoint(x: 209.75, y: 92.4), controlPoint1: CGPoint(x: 202.65, y: 95.4), controlPoint2: CGPoint(x: 205.65, y: 92.4))
        text2Path.addCurveToPoint(CGPoint(x: 214.7, y: 94.35), controlPoint1: CGPoint(x: 211.45, y: 92.4), controlPoint2: CGPoint(x: 213.25, y: 93.05))
        text2Path.addLineToPoint(CGPoint(x: 218.55, y: 90.3))
        text2Path.addCurveToPoint(CGPoint(x: 209.65, y: 86.65), controlPoint1: CGPoint(x: 215.85, y: 87.65), controlPoint2: CGPoint(x: 213.15, y: 86.65))
        text2Path.addCurveToPoint(CGPoint(x: 196.55, y: 99.7), controlPoint1: CGPoint(x: 202.5, y: 86.65), controlPoint2: CGPoint(x: 196.55, y: 90.95))
        text2Path.addCurveToPoint(CGPoint(x: 209.65, y: 112.75), controlPoint1: CGPoint(x: 196.55, y: 108.45), controlPoint2: CGPoint(x: 202.5, y: 112.75))
        text2Path.addCurveToPoint(CGPoint(x: 219.15, y: 108.85), controlPoint1: CGPoint(x: 213.3, y: 112.75), controlPoint2: CGPoint(x: 216.3, y: 111.65))
        text2Path.addLineToPoint(CGPoint(x: 215.05, y: 104.85))
        text2Path.closePath()
        text2Path.moveToPoint(CGPoint(x: 247.3, y: 101.85))
        text2Path.addCurveToPoint(CGPoint(x: 234.85, y: 86.6), controlPoint1: CGPoint(x: 248.25, y: 91.7), controlPoint2: CGPoint(x: 243.1, y: 86.6))
        text2Path.addCurveToPoint(CGPoint(x: 221.75, y: 99.5), controlPoint1: CGPoint(x: 226.85, y: 86.6), controlPoint2: CGPoint(x: 221.75, y: 92))
        text2Path.addCurveToPoint(CGPoint(x: 235.3, y: 112.65), controlPoint1: CGPoint(x: 221.75, y: 107.4), controlPoint2: CGPoint(x: 226.8, y: 112.65))
        text2Path.addCurveToPoint(CGPoint(x: 245.9, y: 108.65), controlPoint1: CGPoint(x: 239.05, y: 112.65), controlPoint2: CGPoint(x: 243.3, y: 111.35))
        text2Path.addLineToPoint(CGPoint(x: 242, y: 104.8))
        text2Path.addCurveToPoint(CGPoint(x: 235.4, y: 107.1), controlPoint1: CGPoint(x: 240.6, y: 106.25), controlPoint2: CGPoint(x: 237.65, y: 107.1))
        text2Path.addCurveToPoint(CGPoint(x: 228.05, y: 101.85), controlPoint1: CGPoint(x: 231.1, y: 107.1), controlPoint2: CGPoint(x: 228.45, y: 104.9))
        text2Path.addLineToPoint(CGPoint(x: 247.3, y: 101.85))
        text2Path.closePath()
        text2Path.moveToPoint(CGPoint(x: 228.15, y: 96.8))
        text2Path.addCurveToPoint(CGPoint(x: 235.05, y: 92), controlPoint1: CGPoint(x: 229.05, y: 93.6), controlPoint2: CGPoint(x: 231.75, y: 92))
        text2Path.addCurveToPoint(CGPoint(x: 241.45, y: 96.8), controlPoint1: CGPoint(x: 238.55, y: 92), controlPoint2: CGPoint(x: 241.05, y: 93.6))
        text2Path.addLineToPoint(CGPoint(x: 228.15, y: 96.8))
        text2Path.closePath()
        text2Path.moveToPoint(CGPoint(x: 276.25, y: 112))
        text2Path.addLineToPoint(CGPoint(x: 276.25, y: 99.05))
        text2Path.addCurveToPoint(CGPoint(x: 265.8, y: 86.95), controlPoint1: CGPoint(x: 276.25, y: 91.3), controlPoint2: CGPoint(x: 271.6, y: 86.95))
        text2Path.addCurveToPoint(CGPoint(x: 257.7, y: 90.65), controlPoint1: CGPoint(x: 262.7, y: 86.95), controlPoint2: CGPoint(x: 260.2, y: 88.2))
        text2Path.addLineToPoint(CGPoint(x: 257.3, y: 87.3))
        text2Path.addLineToPoint(CGPoint(x: 251.85, y: 87.3))
        text2Path.addLineToPoint(CGPoint(x: 251.85, y: 112))
        text2Path.addLineToPoint(CGPoint(x: 257.9, y: 112))
        text2Path.addLineToPoint(CGPoint(x: 257.9, y: 99.4))
        text2Path.addCurveToPoint(CGPoint(x: 264.2, y: 92.5), controlPoint1: CGPoint(x: 257.9, y: 95.65), controlPoint2: CGPoint(x: 260.45, y: 92.5))
        text2Path.addCurveToPoint(CGPoint(x: 270.15, y: 99.1), controlPoint1: CGPoint(x: 268.1, y: 92.5), controlPoint2: CGPoint(x: 270.15, y: 95.35))
        text2Path.addLineToPoint(CGPoint(x: 270.15, y: 112))
        text2Path.addLineToPoint(CGPoint(x: 276.25, y: 112))
        text2Path.closePath()
        text2Path.moveToPoint(CGPoint(x: 282.95, y: 81.05))
        text2Path.addLineToPoint(CGPoint(x: 282.95, y: 87.4))
        text2Path.addLineToPoint(CGPoint(x: 278.35, y: 87.4))
        text2Path.addLineToPoint(CGPoint(x: 278.35, y: 92.65))
        text2Path.addLineToPoint(CGPoint(x: 282.95, y: 92.65))
        text2Path.addLineToPoint(CGPoint(x: 282.95, y: 103.3))
        text2Path.addCurveToPoint(CGPoint(x: 291.8, y: 112.3), controlPoint1: CGPoint(x: 282.95, y: 109.45), controlPoint2: CGPoint(x: 286.45, y: 112.5))
        text2Path.addCurveToPoint(CGPoint(x: 296.85, y: 111.25), controlPoint1: CGPoint(x: 293.65, y: 112.25), controlPoint2: CGPoint(x: 295.1, y: 111.95))
        text2Path.addLineToPoint(CGPoint(x: 295.15, y: 106.05))
        text2Path.addCurveToPoint(CGPoint(x: 292.2, y: 106.8), controlPoint1: CGPoint(x: 294.25, y: 106.5), controlPoint2: CGPoint(x: 293.15, y: 106.8))
        text2Path.addCurveToPoint(CGPoint(x: 289, y: 103.3), controlPoint1: CGPoint(x: 290.3, y: 106.8), controlPoint2: CGPoint(x: 289, y: 105.65))
        text2Path.addLineToPoint(CGPoint(x: 289, y: 92.65))
        text2Path.addLineToPoint(CGPoint(x: 295.85, y: 92.65))
        text2Path.addLineToPoint(CGPoint(x: 295.85, y: 87.4))
        text2Path.addLineToPoint(CGPoint(x: 289.05, y: 87.4))
        text2Path.addLineToPoint(CGPoint(x: 289.05, y: 80.4))
        text2Path.addLineToPoint(CGPoint(x: 282.95, y: 81.05))
        text2Path.closePath()
        text2Path.moveToPoint(CGPoint(x: 324.85, y: 101.85))
        text2Path.addCurveToPoint(CGPoint(x: 312.4, y: 86.6), controlPoint1: CGPoint(x: 325.8, y: 91.7), controlPoint2: CGPoint(x: 320.65, y: 86.6))
        text2Path.addCurveToPoint(CGPoint(x: 299.3, y: 99.5), controlPoint1: CGPoint(x: 304.4, y: 86.6), controlPoint2: CGPoint(x: 299.3, y: 92))
        text2Path.addCurveToPoint(CGPoint(x: 312.85, y: 112.65), controlPoint1: CGPoint(x: 299.3, y: 107.4), controlPoint2: CGPoint(x: 304.35, y: 112.65))
        text2Path.addCurveToPoint(CGPoint(x: 323.45, y: 108.65), controlPoint1: CGPoint(x: 316.6, y: 112.65), controlPoint2: CGPoint(x: 320.85, y: 111.35))
        text2Path.addLineToPoint(CGPoint(x: 319.55, y: 104.8))
        text2Path.addCurveToPoint(CGPoint(x: 312.95, y: 107.1), controlPoint1: CGPoint(x: 318.15, y: 106.25), controlPoint2: CGPoint(x: 315.2, y: 107.1))
        text2Path.addCurveToPoint(CGPoint(x: 305.6, y: 101.85), controlPoint1: CGPoint(x: 308.65, y: 107.1), controlPoint2: CGPoint(x: 306, y: 104.9))
        text2Path.addLineToPoint(CGPoint(x: 324.85, y: 101.85))
        text2Path.closePath()
        text2Path.moveToPoint(CGPoint(x: 305.7, y: 96.8))
        text2Path.addCurveToPoint(CGPoint(x: 312.6, y: 92), controlPoint1: CGPoint(x: 306.6, y: 93.6), controlPoint2: CGPoint(x: 309.3, y: 92))
        text2Path.addCurveToPoint(CGPoint(x: 319, y: 96.8), controlPoint1: CGPoint(x: 316.1, y: 92), controlPoint2: CGPoint(x: 318.6, y: 93.6))
        text2Path.addLineToPoint(CGPoint(x: 305.7, y: 96.8))
        text2Path.closePath()
        text2Path.moveToPoint(CGPoint(x: 329.55, y: 87.35))
        text2Path.addLineToPoint(CGPoint(x: 329.55, y: 112))
        text2Path.addLineToPoint(CGPoint(x: 335.65, y: 112))
        text2Path.addLineToPoint(CGPoint(x: 335.65, y: 99))
        text2Path.addCurveToPoint(CGPoint(x: 341.8, y: 92.75), controlPoint1: CGPoint(x: 335.65, y: 94.45), controlPoint2: CGPoint(x: 338.6, y: 92.75))
        text2Path.addCurveToPoint(CGPoint(x: 346.2, y: 94.35), controlPoint1: CGPoint(x: 343.8, y: 92.75), controlPoint2: CGPoint(x: 344.95, y: 93.3))
        text2Path.addLineToPoint(CGPoint(x: 348.95, y: 89.05))
        text2Path.addCurveToPoint(CGPoint(x: 342.6, y: 86.7), controlPoint1: CGPoint(x: 347.6, y: 87.7), controlPoint2: CGPoint(x: 345.15, y: 86.7))
        text2Path.addCurveToPoint(CGPoint(x: 335.65, y: 90.2), controlPoint1: CGPoint(x: 340.1, y: 86.7), controlPoint2: CGPoint(x: 337.55, y: 87.15))
        text2Path.addLineToPoint(CGPoint(x: 335.2, y: 87.35))
        text2Path.addLineToPoint(CGPoint(x: 329.55, y: 87.35))
        text2Path.closePath()
        text2Path.lineJoinStyle = .Round;

        BCStyleKit.mintL.setFill()
        text2Path.fill()
    }

    public class func drawGradeControl(grade grade: CGFloat = 1) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Color Declarations
        let grapeFruitD = UIColor(red: 0.855, green: 0.267, blue: 0.325, alpha: 1.000)
        let bittersweetD = UIColor(red: 0.914, green: 0.341, blue: 0.247, alpha: 1.000)
        let sunflowerD = UIColor(red: 0.965, green: 0.733, blue: 0.259, alpha: 1.000)
        let grassD = UIColor(red: 0.549, green: 0.757, blue: 0.322, alpha: 1.000)

        //// Variable Declarations
        let sliderValue: CGFloat = 315 * grade
        let gradeColor = grade < 0.6 ? grapeFruitD : (grade < 0.7 ? bittersweetD : (grade < 0.8 ? sunflowerD : (grade < 0.9 ? grassD : BCStyleKit.mintD)))
        let letterGrade = grade < 0.6 ? "F" : (grade < 0.7 ? "D" : (grade < 0.8 ? "C" : (grade < 0.9 ? "B" : "A")))

        //// Rectangle Drawing


        //// Oval Drawing
        let ovalPath = UIBezierPath()
        ovalPath.moveToPoint(CGPoint(x: 16, y: 115))
        ovalPath.addCurveToPoint(CGPoint(x: 116, y: 15), controlPoint1: CGPoint(x: 16, y: 59.77), controlPoint2: CGPoint(x: 60.77, y: 15))
        ovalPath.addCurveToPoint(CGPoint(x: 216, y: 115), controlPoint1: CGPoint(x: 171.23, y: 15), controlPoint2: CGPoint(x: 216, y: 59.77))
        ovalPath.lineCapStyle = .Round;

        gradeColor.setStroke()
        ovalPath.lineWidth = 20
        CGContextSaveGState(context)
        CGContextSetLineDash(context, 0, [sliderValue, 330], 2)
        ovalPath.stroke()
        CGContextRestoreGState(context)


        //// Text Drawing
        let textRect = CGRect(x: 59, y: 52, width: 115, height: 78)
        let textStyle = NSMutableParagraphStyle()
        textStyle.alignment = .Center

        let textFontAttributes = [NSFontAttributeName: UIFont(name: "NexaBold", size: 80)!, NSForegroundColorAttributeName: UIColor.blackColor(), NSParagraphStyleAttributeName: textStyle]

        let textTextHeight: CGFloat = NSString(string: letterGrade).boundingRectWithSize(CGSize(width: textRect.width, height: CGFloat.infinity), options: NSStringDrawingOptions.UsesLineFragmentOrigin, attributes: textFontAttributes, context: nil).size.height
        CGContextSaveGState(context)
        CGContextClipToRect(context, textRect)
        NSString(string: letterGrade).drawInRect(CGRect(x: textRect.minX, y: textRect.minY + (textRect.height - textTextHeight) / 2, width: textRect.width, height: textTextHeight), withAttributes: textFontAttributes)
        CGContextRestoreGState(context)
    }

    //// Generated Images

    public class var imageOf_5Elaborated: UIImage {
        if Cache.imageOf_5Elaborated != nil {
            return Cache.imageOf_5Elaborated!
        }

        UIGraphicsBeginImageContextWithOptions(CGSize(width: 200, height: 200), false, 0)
            BCStyleKit.draw_5Elaborated()

        Cache.imageOf_5Elaborated = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return Cache.imageOf_5Elaborated!
    }

    public class var imageOf_15Elaborated: UIImage {
        if Cache.imageOf_15Elaborated != nil {
            return Cache.imageOf_15Elaborated!
        }

        UIGraphicsBeginImageContextWithOptions(CGSize(width: 200, height: 200), false, 0)
            BCStyleKit.draw_15Elaborated()

        Cache.imageOf_15Elaborated = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return Cache.imageOf_15Elaborated!
    }

    public class var imageOf_12Elaborated: UIImage {
        if Cache.imageOf_12Elaborated != nil {
            return Cache.imageOf_12Elaborated!
        }

        UIGraphicsBeginImageContextWithOptions(CGSize(width: 400, height: 200), false, 0)
            BCStyleKit.draw_12Elaborated()

        Cache.imageOf_12Elaborated = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return Cache.imageOf_12Elaborated!
    }

    //// Customization Infrastructure

    @IBOutlet var _5ElaboratedTargets: [AnyObject]! {
        get { return Cache._5ElaboratedTargets }
        set {
            Cache._5ElaboratedTargets = newValue
            for target: AnyObject in newValue {
                target.performSelector(NSSelectorFromString("setImage:"), withObject: BCStyleKit.imageOf_5Elaborated)
            }
        }
    }

    @IBOutlet var _15ElaboratedTargets: [AnyObject]! {
        get { return Cache._15ElaboratedTargets }
        set {
            Cache._15ElaboratedTargets = newValue
            for target: AnyObject in newValue {
                target.performSelector(NSSelectorFromString("setImage:"), withObject: BCStyleKit.imageOf_15Elaborated)
            }
        }
    }

    @IBOutlet var _12ElaboratedTargets: [AnyObject]! {
        get { return Cache._12ElaboratedTargets }
        set {
            Cache._12ElaboratedTargets = newValue
            for target: AnyObject in newValue {
                target.performSelector(NSSelectorFromString("setImage:"), withObject: BCStyleKit.imageOf_12Elaborated)
            }
        }
    }

}
